- exercise/staff_views.py
- exercise/urls.py
- templates/course/teachers_view.html
- templates/exercise/remove_exercise.html
With this functionality, teacher's can remove exercises in the teachers' view.
> Added remove exercise button to teachers' view

- exercise/exercise_models.py
- templates/course/view_instance.html
Fixes (at least somewhat) #154.
> Add late submission details to UI

- exercise/exercise_models.py
> Fixes late submission

- django_shibboleth/views.py
- exercise/exercise_models.py
- templates/course/_course_menu.html
- templates/course/assistants_view.html
- templates/course/teachers_view.html
This pull request fixes some UI issues:
* The ordering of the exercises is now correct in teacher's and assistants' view
* Fixed one typo in Late submissions
* Better chosen icons in teacher's view
* Teacher's and assistants' view had different names in the view and in the menu.
> UI enhancements

- django_shibboleth/views.py
Fixing issues with Shibboleth seems to be a hard task. Hopefully it now finally works...
Fixes issues is #162 and #163
> Fixing Shibboleth, once again

- doc/README.md
- notification/south_migrations/0001_initial.py
- selenium_test/test/course_archive_page_test.py
Maby we get Jenkins to comment on this PR...
> Fix bug stopping coverage testing.

- locale/fi/LC_MESSAGES/django.po
In the Finnish translation, there were some minor typos. Adds also some new missing translations.
> Fix a few translation typos and add new translations

- lib/helpers.py
> Treat numbers as safe filename characters

- README.md
- api/permissions.py
- userprofile/api.py
Fix for the issue #207. The main issue seemed to be that the implementation was made for Tastypie 0.9.11 or older which is not supported anymore.
> Fix for unauthenticated REST API request

- api/permissions.py
> Single resource GET as superuser -vulnerability fixed

- course/models.py
- course/views.py
- exercise/exercise_models.py
These changed seemed to get "enroll" action for student to work on course with enrollment exercise.
> Small fixes to get enrollment working

- course/long_urls.py
- course/templates/course/_course_menu.html
- course/templates/course/participants.html
- course/views.py
Adds participant listing which is visible to course staff members. This is an initial version and can be extended after there is a view for each student showing their progress.
> Participant list

- userprofile/models.py
- userprofile/tests.py
Provides a better string format for users, shown for example when selecting course assistants.
> Better __str__ for UserProfile

- assets/css/main.css
- assets/js/aplus.js
- course/templates/course/course_base.html
- edit_course/exercise_forms.py
- selenium_test/test/main_navigation_test.py
The main menu will be always visible by fixing the menu position when a content page is scrolled down.
> Main menu modifications

- course/templates/course/index.html
Make the course images in the front page clickable. Those are nice and big targets to click.
> Make course images clickable

- course/management/commands/scale_grade_to.py
- exercise/submission_models.py
This is useful for example when a single students grades need to be zeroed out on a course.
> Add management command to scale student's points on a course instance

- exercise/static/exercise/poll.js
Fix issue where graded but unofficial submissions wouldn't automatically refresh to results
> Fix unofficial submission polling bug

- apps/templates/plugins/view_tab.html
- course/templates/course/archive.html
- course/templates/course/course_base.html
- course/templates/course/groups.html
- course/templates/course/module.html
- course/templates/course/staff/group_delete.html
- course/templates/course/staff/group_edit.html
- course/templates/course/staff/groups.html
- course/templates/course/staff/participants.html
- diploma/templates/diploma/list.html
- edit_course/templates/edit_course/edit_course_base.html
- edit_course/templates/edit_course/signin_as_user.html
- exercise/templates/exercise/exercise_base.html
- exercise/templates/exercise/results.html
- exercise/templates/exercise/staff/analytics.html
- exercise/templates/exercise/staff/assess_submission.html
- exercise/templates/exercise/staff/edit_submitters.html
- exercise/templates/exercise/staff/inspect_submission.html
- exercise/templates/exercise/staff/list_submissions.html
- exercise/templates/exercise/staff/results.html
- exercise/templates/exercise/staff/submissions_summary.html
- exercise/templates/exercise/staff/user_results.html
- exercise/templates/exercise/submission.html
- exercise/templates/exercise/toc.html
- external_services/templates/external_services/lti_form.html
- userprofile/templates/userprofile/login.html
- userprofile/templates/userprofile/logout.html
- userprofile/templates/userprofile/privacy.html
- userprofile/templates/userprofile/profile.html
> Reverse order of information in title

- templates/base.html
Combines the user profile and logout links under a shared dropdown
> Navbar dropdown

- external_services/api/authentication.py
- external_services/api/parsers.py
- external_services/api/serializers.py
- external_services/api/tests.py
- external_services/api/views.py
> LTI 1.1 fixes

- exercise/exercise_summary.py
I.e. in the order they appear in the forest.
Assume that anything interesting is a leaf. It should be relatively simple
to modify this to inspect the whole forest if needed in the future.
It should be possible to implement this also using search_exercises
which returns the non-root nodes of the forest as a list. That might lead
to a simpler solution code-wise but I feel tree traversal is the more intuitive
solution.
> Show exercises in correct order on all results page

- course/templates/course/_course_menu.html
* Use semantically correct UL tag instead of DIV and add aria-labelledby
* Do not wrap the dropdown contents inside a non-semantic H4 tag, and use
bootstrap's .h4 CSS class instead
> Sanify language selection dropdown markup

- exercise/static/exercise/language_link.js
- exercise/templates/exercise/exercise.html
for user-friendly wrong language alerts
> Implement language-changing links

- exercise/api/views.py
**This is very rough. Please review the code and try to see if there are some mistakes.**
This enables more or less the same functionality as the "Batch assess" in the teacher menu but instead of JSON it uses the DRF and HTTP POST.
Currently this: 
* allows the POST to create a new submission if teacher API key is used (no other keys accepted)
* checks that the new submission owner/submitter is enrolled to the course
* accepts students by either email or student id
> API: allow POST by teacher to create a new submission

- assets/js/aplus.js
Wrap the remaining plugins inside aplus.js with anonymous functions. The closures help to keep the scope less populated inside the aplus.js.
Requested by Jaakko.
> Wrap all functions with anonymous functions inside aplus.js.

- course/api/full_serializers.py
- course/api/views.py
- course/models.py
- lib/helpers.py
These relate to the development of the automatic tagging script 
at [JoonatanPartanen/o1_auto_tag](https://github.com/JoonatanPartanen/o1_auto_tag)
> Tagging and course hook improvements, API creation of usertags

- assets/js-translations/teacher.fi.json
- assets/js/aplus.js
- assets/js/filter.js
- exercise/templates/exercise/staff/_submissions_table.html
- templates/base.html
Currently the filtering of results only sees if it can find the typed string inside the data. Jaakko wished that filtering would be improved.
The proposed improvements allow the teacher to filter results with comparison operators (<, >, >=, <=, ==, !=) and create own regex options for filtering.
> Improved filtering. Options to filter with comparison operators and regex.

- assets/js-translations/teacher.fi.json
- exercise/staff_views.py
- exercise/static/exercise/css/loading_animation.css
- exercise/static/exercise/css/results_staff.css
- exercise/static/exercise/results_staff.js
- exercise/templates/exercise/staff/results.html
- locale/fi/LC_MESSAGES/django.po
Currently the Results page for teachers is very minimal and quite frankly, useless. Tasked by Juho and Jaakko, I have been making some improvements to it. Added functionality to export the table data. Option to select from the exercise pool. Option to filter based on tags. Option to see different data indicators.
NOTE: Filtering relies on my other pull requests. I would also hope someone could test this with more student data. I have not found a way to test this reliably on large student result data.
> Improved the results page for end of course for teachers.

- assets/css/main.css
This class is needed to separate correct answers from neutral. Mooc-grader PR: Aalto-LeTech/mooc-grader#51
> Add css class to the neutral option

- assets/js-translations/teacher.fi.json
- assets/js/ajax_search_select.js
- assets/js/aplus.js
- course/forms.py
- edit_course/course_forms.py
- exercise/forms.py
- exercise/templates/exercise/staff/edit_submitters.html
- lib/fields.py
- templates/base.html
- userprofile/api/views.py
- userprofile/permissions.py
Search Users from API instead of loading all 10000+ UserProfiles to the HTML template.
The pages containing search fields should download much faster.
> Use ajax in search fields.

- assets/js/ajax_search_select.js
- course/forms.py
- exercise/forms.py
- lib/fields.py
- locale/fi/LC_MESSAGES/django.po
> AJAX search quality improvement and fixes

- doc/DEPLOYMENT.md
Fixing typos and adding a couple of missing commands to the deployment guide
This pull request affects only documentation, no need for extra testing.
The documentation has been updated
> Small fixes to Apache setup in deployment guide

- doc/README.md
- selenium_test/README.md
Updates the `doc/README.md` (documentation on how to start the development environment) so that development would be easier to start. Also the documentation on Selenium tests have been moved to `doc/README.md` for continuity.
Apart from installing the software (docker, docker-compose, python), that A+ development requires, these instructions have been tested. The geckodriver for Selenium-tests was not correctly installed when following the earlier instructions for Selenium-tests, but that has been fixed. 
This would update the relevant documentation.
> Update doc/README.md 

- doc/DEPLOYMENT.md
- locale/fi/LC_MESSAGES/django.po
- templates/accessibility_issues_en.html
- templates/base.html
- templates/institution_accessibility_text_en.html
- userprofile/templates/userprofile/accessibility.html
- userprofile/urls.py
- userprofile/views.py
It's a legal requirement that we show a statement of our compliance with the EU accessibility directive.
This adds the relevant templates.
No translations are done yet. 
*Remember to add or update unit tests for new features and changes.*
*Remember to also run all tests available in the project in order to see that they still pass.*
*Describe here what needs to be tested MANUALLY due to these changes.*
*Think of what is affected by these changes and could become broken (and can not be easily tested automatically)?*
> Accessibility statement

- exercise/api/custom_serializers.py
- exercise/api/serializers.py
Add key `submissions_and_points` list to `/api/v2/courses/<course-id>/points/me/`
```
"submissions_and_points": [
{
"id": 567,
"url": "http://0.0.0.0:8000/api/v2/submissions/567/",
"submission_time": "2020-07-24T08:55:11.895107Z",
"grade": 10
},
{
"id": 566,
"url": "http://0.0.0.0:8000/api/v2/submissions/566/",
"submission_time": "2020-07-24T08:54:24.499804Z",
"grade": 10
}
]
```
Fixes #647
*Remember to add or update unit tests for new features and changes.*
*Remember to also run all tests available in the project in order to see that they still pass.*
*Describe here what needs to be tested MANUALLY due to these changes.*
*Think of what is affected by these changes and could become broken (and can not be easily tested automatically)?*
*Don't forget to update the documentation if it is …
> Show submission points in course points API endpoint

- exercise/exercise_models.py
- locale/fi/LC_MESSAGES/django.po
Fix bug where group id was treated as None if it was equal to 0.
*Remember to add or update unit tests for new features and changes.*
*Remember to also run all tests available in the project in order to see that they still pass.*
*Describe here what needs to be tested MANUALLY due to these changes.*
*Think of what is affected by these changes and could become broken (and can not be easily tested automatically)?*
> Fix group id bug

- course/viewbase.py
The lack of AnonymousUser check when retrieving user-related data (after the PR https://github.com/apluslms/a-plus/pull/632 was merged) caused some problems on submitting specific exercises and four selenium tests broke. This PR adds a check that user is not anonymous when retrieving user-related course data.
* Unit tests and selenium tests pass
* Manually tested by checking that submitting the exercises where tests previously broke now works
* No, not relevant
> Fix AnonymousUser bug

- exercise/management/commands/list_exercises_services.py
- lib/localization_syntax.py
*Provide an overview of the changes and their purpose: what, why, how.*
*Remember to add or update unit tests for new features and changes.*
*Remember to also run all tests available in the project in order to see that they still pass.*
*Describe here what needs to be tested MANUALLY due to these changes.*
*Think of what is affected by these changes and could become broken (and can not be easily tested automatically)?*
> Add management command to list exercise service usage

- doc/README.md
Add some steps that were missing during the development of sass.
> Add instructions to set up sass. Add syntax highlight and indentation

- doc/README.md
Fix small typo in the documentation
> Fix small typo in the documentation

- course/templates/course/_course_menu.html
- templates/base.html
Fixes #714
Tested manually with [ChromeVox](https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en)
The system design document has a mention of this issue. Therefore, the system design document needs to be updated.
> Remove the role="presentation" fom the <li> tags inside navigation menus 

- course/cache/menu.py
- course/views.py
- In course/cache/menu.py: Check that a course is visible to students before adding it into the menu.
- In course/views.py: Create a list of all course instances (filtering out courses not visible for current user) before checking which courses the user has enrolled in.
Fixes #684 
Unit tests and Selenium tests have been run. I did not add any new tests.
Manual testing:
- Create a new course instance and make it open for current date
- Register for the course instance as a student
- Mark the course instance as not visible for students
- Check that the enrolled student does not see the course instance
No.
No.
> Hide courses marked as not visible to students from students in UI

- selenium_test/test/edit_exercise_page_test.py
- selenium_test/test/edit_module_page_test.py
- selenium_test/test/file_upload_grader_test.py
- selenium_test/test/home_page_test.py
- selenium_test/test/locators.py
- selenium_test/test/login_test.py
- selenium_test/test/main_navigation_test.py
- selenium_test/test/my_ajax_exercise_grader_test.py
- selenium_test/test/my_first_exercise_test.py
- selenium_test/test/staff_page_test.py
- selenium_test/test/submissions_page_test.py
- selenium_test/test/teacher_feedback_test.py
- selenium_test/test/test_initializer.py
- selenium_test/test/user_permissions_test.py
- selenium_test/test_data.json
Selenium tests with Headless settings can be automated in the CI pipeline
I ran the selenium tests one by one and all at once using bot headful and headless settings.
There are no changes that require to update the documentation.
> Fix Selenium tests and add headless browser settings

- apps/admin.py
**What?**
The Admin interface for the HTML plugins is updated.
**Why?**
Currently, the Admin users must click on each of the HTML plugins records to access information related to the course instance Id, and every time they click on one of the HTML plugins the admins do not know if they are accessing the correct record.
**How?**
Modifying the Admin Views in Django
Fixes #769
I verified that the information was shown as expected.
**Did you test …
> Improve Admin interface for HTMLPlugins

- doc/DEPLOYMENT.md
- doc/apache2/aplus-apache2.conf
- doc/apache2/aplus-api-uwsgi.service
- doc/apache2/aplus-web-uwsgi.service
- doc/nginx/aplus-api-uwsgi.service
- doc/nginx/aplus-nginx-shib.conf
- doc/nginx/aplus-nginx.conf
- doc/nginx/aplus-web-uwsgi.service
- doc/uwsgi-aplus-api.ini
- doc/uwsgi-aplus-web.ini
- requirements.txt
- requirements_prod.txt
This pull request adds instructions about using NGINX dynamic modules to the deployment documentation, as well as improves documentation in other parts.
These changes are a result of the Aalto A+ exam server deployment and are currently used in production.
> Add instructions for using NGINX dynamic modules and small doc improvements

- doc/README.md
**What?**
The GNU gettext package is added to the list of prerequisites.
**Why?**
This package is required to compile the translations
**How?**
the links for windows and ubuntu installers are added to the doc/README.md file
> Update README file for Django translations

- course/admin.py
- notification/admin.py
- userprofile/admin.py
**What?**
Improved the performance of the Notification Django Admin view
**Why?**
Currently, the UI may crash or may return a timeout error when an admin user tries to access the details of any notification.
**How?**
`search_fields` and `autocomplete_fields` are added to the admin.py pages
**SQL Query previous to this PR**
**SQL Query after this PR**
**Think of what is affected by these changes and could become …
> Improve performance Notification Django Admin view

- apps/admin.py
- course/admin.py
- deviations/admin.py
- diploma/admin.py
- exercise/admin.py
- external_services/admin.py
- news/admin.py
- notification/admin.py
- threshold/admin.py
- userprofile/admin.py
- userprofile/models.py
- userprofile/tests.py
**What?**
Improve the usability of the A+ admin interface by increasing page load performance, adding search functionality and exposing previously hidden fields.
**Why?**
A+ admins waste a lot of time using the admin interface because of its slowness and lacking features.
**How?**
- For every model that references the `UserProfile` model, the referencing field was added to `raw_id_fields` in the corresponding `ModelAdmin` class. This turns the field's input control into a simple textbox with a search functionality, instead of a pre-populated dropdown menu. With large numbers of users, populating the dropdown menu was very slow.
- Added some model fields to `search_fields` for every corresponding `ModelAdmin`. This adds a search box onto the list page of the admin interface, and makes all …
> Improve the usability of the admin insterface. Fixes #707

- aplus/urls.py
- doc/nginx/shibboleth2.xml
- shibboleth_login/urls.py
- userprofile/templates/userprofile/login.html
Add back the Aalto login button that was replaced by Haka login
button in recent commit. Now both local Aalto login button
and Haka login button for external users is shown.
Closes #815.
**What?**
Making this through pull request to check with others whether the URL management style is good, or whether it would be better done some other way. This works at minus.cs.aalto.fi. (Rest of PR template skipped)
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
**What …
> Add separate button for Aalto login.

- .github/workflows/Dockerfile
- .github/workflows/tests.yml
- selenium_test/grader/exercises/views.py
- selenium_test/run_servers.sh
- selenium_test/test/page_objects.py
- selenium_test/test/test_initializer.py
**What?**
Fixes the broken selenium tests and adds the necessary configuration to run the tests automatically on push to GitHub. Additionally, the Dockerfile added to .github/workflows/ can be used to run manage commands and the tests.
**Why?**
People don't always run the tests before submitting a PR. This PR allows the reviewer (and the submitter) to see whether there is a problem easily.
**How?**
Adds a tests.yml file that configures the tests and a Dockerfile that installs the requirements and can then be used to run the tests. The workflow first builds the docker image and caches it (or takes it from the cache), then it runs the unit and selenium tests in parallel.
The tests are run automatically and pass on my fork. …
> Add automatic testing on push to GitHub and fix tests

- .github/workflows/Dockerfile
- .github/workflows/tests.yml
**What?**
Runs compilemessages before running tests in the github ci pipeline.
**Why?**
Tests fail otherwise
Checked that the tests pass on github.
> run compilemessages before running tests in github ci pipeline

- aplus/local_settings.example.py
- aplus/settings.py
- userprofile/static/userprofile/login.css
- userprofile/templates/userprofile/login.html
- userprofile/views.py
**What?**
Improve login page:
- fix layout of login boxes (so buttons don't usually overflow containers) and containers are aligned (and none on following rows float accidentally to the right)
- improve contrast of the "show more login options" button to fulfill accessibilty requirements
- provide option to disable Haka login (requested from Tampere)
**Why?**
Read above
**How?**
- Login box widths increased by increasing the width of containers on medium and large screens
- Login box alignments fixed with clearfixes
- Option to disable Haka login with a variable flag in `settings.py`
Fixes #821
Fixes #833 
* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updatin …
> Improve login page (fix layouts and add option to disable Haka login)

- assets/js-translations/teacher.fi.json
- exercise/api/csv/aggregate_points.py
- exercise/static/exercise/results_staff.js
- exercise/templates/exercise/staff/results.html
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
**What?**
Modifications to results view to 1) provide an alternative column format that should be compatible with what Sisu accepts as CSV; 2) Organization information of students
**Why?**
Sisu needs to be supported starting this semester. A+ now supports Haka login from multiple organizations, so it may be important for teacher to separate students based on their home university.
**How?**
Changing the existing column ordering, e.g. "Name" column has been separated into last name and first name, also several new columns needed by Sisu are added, even though for now they are left empty, because A+ does not calculate grades. The idea is that teacher can do a csv export to another tool (e.g., Excel), calculate grades based on the scores in csv into grade section, fill the information columns …
> Sisu format

- api/urls_v2.py
- course/api/full_serializers.py
- course/api/serializers.py
- course/api/views.py
Implements GET endpoints for course-specific news list.
Visibility of news is filtered in the similar way than in the
user interfaces, depending on whether user is course staff,
internal or external student. Closes #824.
**What?**
As described in commit message
**Why?**
This was requested by the IntelliJ plugin development team. [Related issue in their github](https://github.com/Aalto-LeTech/intellij-plugin/issues/537).
**How?**
Adds a new route under the course API for querying the news on the course.
Fixes #824 
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+ …
> Add API endpoint for course news

- edit_course/views.py
- exercise/staff_views.py
- lib/logging.py
**What?**
Adds log events that are required by Aalto security policy.
**Why?**
The events that need to be logged are documented in [this document](https://www.aalto.fi/system/files/2020-09/Aalto-yliopiston%20lokis%C3%A4%C3%A4nt%C3%B6%20versio%201.3_0.pdf).
**How?**
Implements a new SecurityLog singleton class in lib/logging.py that provides a consistent logging format. It outputs user performing the action, IP address from which the request came in, type of log event, and then additional information related to the event.
The log output looks like this:
```
[2021-08-11 21:08:40,226] (?/?): login-failed: {'username': 'jgfjfld', 'password': '********************'}
[2021-08-11 21:08:56,340] (user-1/192.168.56.1): login:
[2021-08-11 21:09:17,852] (user-1/192.168.56.1): logout:
[2021-08-14 …
```
> Security log events as required by Aalto policy

- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
- templates/base.html
**What?**
Add a link leading to a feedback form to the footer.
**Why?**
So users can easily give feedback on the UI, etc.
**How?**
By editing the base template and adding a translation.
> Add feedback link to footer

- exercise/static/exercise/css/results_staff.css
**What?**
Move margin from points table to surrounding div so it remains while
scrolling. Move sticky table header row to closer to top so other
cells don't peek from above.
**Why?**
Because the margin didn't remain when scrolling vertically, and other rows "peeked" from above the header cells (which were lower down to try to keep the margin).
**How?**
Read **What?**
Checked in browser while running the code locally and also with editing within …
> Adjust results table top margin

- course/management/commands/delete_instance.py
- course/models.py
- userprofile/management/commands/delete_users.py
**What?**
According to (to-be-approved) privacy notice, old course instances (including exercise submissions) and old inactive user accounts should be removed after specified time. This pull request adds Django manage scripts to do that.
**Why?**
Because of privacy notice. Also Tampere has similar requirements.
**How?**
Using manage scripts
**Think of what is …
> Removing old course instances and users

- course/api/full_serializers.py
- course/api/tests.py
- course/api/views.py
- course/tests.py
- lib/fields.py
**What?**
Add POST and PUT methods to courses API so that courses can be added and modified using the API. Requires admin rights. See additional information from commit messages.
**Why?**
This was requested by Tampere University, but it could be useful also to us in some form later, when we proceed with integrations with Aalto systems.
**How?**
See the related four commits for details. Also a few basic tests were added (although there would be room for much better test coverage, as always.
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull …
> Adding and modifying courses from API

- exercise/templates/exercise/staff/_assessment_panel.html
- exercise/templates/exercise/staff/_resubmit_modal.html
- exercise/templates/exercise/staff/inspect_submission.html
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
- selenium_test/test/locators.py
**What?**
The labels of several UI elements on the submission inspection page have been changed.
**Why?**
According to feedback received from users, some of the labels were unclear.
**How?**
The labels have been changed as seen in the images below:
Tested that the new labels appeared correctly in English and Finnish.
*Clean up your git commit …
> Change UI element labels on inspect page

- deviations/views.py
- exercise/exercise_summary.py
**What?**
There were severe performance issues in the deviation list view and the "my submissions" list. There were multiple database queries executed for each row in these lists, which caused the performance to decrease with large numbers of items.
**Why?**
Slowness reported by users.
**How?**
With the use of `select_related` and `prefetch_related`, the lists now execute a constant number of queries on page load regardless of the number of items.
**What type of test did you …
> Improve performance of deviation list and submission list

- exercise/templates/exercise/submission.html
- exercise/templates/exercise/submission_plain.html
**What?**
Assistant feedback is now hidden in the submission popup and the standalone submission page when the submission feedback reveal rule evaluates to false.
**Why?**
There was a bug in the delayed feedback update where assistant feedback would be visible, even though automatic feedback and points were hidden as intended.
**How?**
Check whether feedback should be revealed before rendering the assistant feedback into the submission templates.
**What type of test did you …
> Hide assistant feedback when feedback is delayed

- exercise/views.py
**What?**
This PR fixes the problem where model and template files are decoded using wrong character encoding when viewed in A+.
**Why?**
This problem was brought up by a course TA.
**How?**
Change the GET request response encoding to UTF-8.
Fixes #927
The template and model files were tested to no longer show garbled or misrepresented characters when viewed in A+.
**Think of what is affected by these changes and …
> Fix template and model file encoding

- edit_course/operations/configure.py
- exercise/protocol/aplus.py
- exercise/views.py
- lib/remote_page.py
**What?**
Send the instance id permission with requests to co
**Why?**
Newest Git Manager requires permissions on all endpoints.
**How?**
Populate permissions on requests.
Seems to work.
If it works on one browser, it works on all.
> Add permissions to remote page accesses

- course/permissions.py
**What?**
Fix couple small JWT access issues.
**Why?**
MOOC Jutut couldn't access an exercise when the module was not open.
> Fix couple small JWT access issues

- lib/api/authentication/grader.py
**What?**
Add exercise read permissions to submission tokens.
**Why?**
Otherwise Jutut requests are denied.
**How?**
Add permissions in grader.py on authentication.
> Fix Jutut access

- course/viewbase.py
**What?**
Fix an issue when A+ API endpoints (all or some?) crash when the URL includes the hl GET query parameter. The server is not supposed to crash when query parameters are added to the URL.
**Why?**
It caused a+ shows exception page where it should show 404 page. Caused by unhandled exception due to missing handle_exception method on the particular class.
**How?**
relocate an handle_exception method to more relevant class to handle the exception.
Fixes EDIT 767
**What type …
> fix: hl param api crash due to unhandled exception

- exercise/staff_views.py
- exercise/templates/exercise/staff/_submissions_table_compact.html
- exercise/templates/exercise/staff/inspect_submission.html
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
The Final label is used in Inspect submissions' submission list
also for submissions that are not marked as final. This modification
uses a different label when Final is not appropriate. It also
clarifies whether the best or last submission is chosen for grading.
**What?**
See above. This is issue EDIT-768 in Jira.
**Why?**
As described in Jira
**How?**
[ANSWER HERE]
Tested different combinations with few submissions by same user.
**Did you …
> Clarifying the Final label in Inspect submissions view

- exercise/submission_models.py
**What?**
Edit the order of imports according to the style guide and remove unused constant ``PASS_MIME`` in ``submission_models.py``
> Fix import order and remove unused constant in submission_models.py

- doc/README.md
**What?**
This PR adds documentation to README.md about how model inheritance works in A+.
**Why?**
The recent model inheritance optimizations changed the way inherited models are queried.
**How?**
New chapter in README.md.
> Documentation about model inheritance

- course/permissions.py
- course/views.py
- diploma/models.py
- edit_course/managers.py
- edit_course/operations/configure.py
- edit_course/tests.py
- edit_course/views.py
- exercise/cache/points.py
- exercise/exercise_summary.py
- exercise/exercisecollection_models.py
- exercise/staff_views.py
- exercise/templates/exercise/staff/_assessment_panel.html
- notification/models.py
- threshold/models.py
**What?**
This commit optimizes queries where the count of some queryset was compared to 0 to check the existence of some objects.
**Why?**
`.exists()` is usually faster than `.count()`. This was discussed in a comment on #973.
**How?**
All occurrences where the result of `.count()` was compared to 0 (either `== 0` or `> 0`), have been replaced with an `.exists()` call.
**Think of what is affected by these …
> Use exists() instead of comparing count() to 0

- locale/en/LC_MESSAGES/django.po
**What?**
This PR fixes a typo in the deviation list templates.
**Why?**
Typo bad
**How?**
Change "Remote selected deviations" to "Remove selected deviations".
Fixes #970
> Fix typo in deviation list templates

- aplus/celery.py
- aplus/local_settings.example.py
- aplus/settings.py
New settings variable SIS_ENROLL_DELAY can be used to add delay
between consecutive requests for enrollments in SIS. For example
Aalto's API gateway has a rate limit for incoming requests.
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up …
> Add rate limit for outgoing SIS enrollment requests

- deviations/viewbase.py
In some circumstances the revised deadline deviations code tried
to add same deviation multiple times to DB, because get_submitters()
might have returned multiple copies of the same user profile.
Needed to disable three tests temporarily for a reason described
in issue #1003.
Fixes #993.
Tested in minus, and this fix seems to work.
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
[ADD A DESCRIPTION …
> Deadline deviations: fix crash due to DB uniqueness violation

- api/urls_v2.py
- course/api/full_serializers.py
- course/api/views.py
- exercise/api/full_serializers.py
- exercise/api/views.py
- lib/api/serializers.py
- lib/api/statistics.py
Returns number of submissions, and number of distinct users
submitting over time window given as query parameters.
These statistics can be queried for a specific course,
for a specific exercise, or through all courses in system.
Closes #989.
**What?**
Initial implementation of statistics API end point. Idea is to continue this work by developing a separate tool for collecting the data using this API. The tool would then create different visualizations of the data with regular updates. The API is intentionally open for logged in A+ users. In future the API could be extended with other metrics, for example based on user requests.
Not sure if the current way of using ViewSets is good, but I'm sure you will tell me :-)
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE] …
> API endpoint for getting submission statistics

- lib/logging.py
- requirements.txt
Aalto ITS requires ArcSight Common Event Format (CEF) for the
stored logs. Convert the SecurityLog output to follow this format,
using format_cef library.
**What?**
As said above. We may later need to adjust logger settings and possibly other details based on ITS feedback, but with this commit we would have CEF formatting in place.
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
[ADD A DESCRIPTION ABOUT WHAT YOU TESTED …
> Apply CEF format in security logs

- assets/js/participants.js
- course/templates/course/staff/participants.html
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
Show more clearly the counts of different enrollment statuses in the
participants list view.
**What?**
This is the promised follow-up pull request to #1011 , to clarify texts related to participant counts.
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up your git …
> Clarify enrollment counts in the participants view

- assets/js/aplus.js
- exercise/exercise_models.py
- exercise/static/exercise/assessment.js
- exercise/templates/exercise/_model_files.html
- exercise/templates/exercise/_template_files.html
- exercise/views.py
Adds download buttons to model answer and template modals
Fixes #894
**What?**
Adds download buttons to "Show model answer" and "Show exercise template" modals
**Why?**
This allows the user to download the file instead of just seeing the contents
**How?**
Add button to frontend that calls backend with ?download=yes parameter and backend knows then to serve the files with Content-Disposition header which causes browser to initiate downloading
Fixes #894
**What type of test did …
> Add download buttons to modal dialogs

- exercise/api/views.py
**What?**
Add an API endpoint for resubmitting submissions to grading.
Only course staff can use the resubmit API.
**Why?**
This was requested for O1.
**How?**
See the code.
Fixes #1008
Tested that the new API endpoint works and has the correct permissions.
> API endpoint for regrading submissions

- api/urls_v2.py
- course/api/full_serializers.py
- exercise/api/csv/views.py
- exercise/static/exercise/results_staff.js
- exercise/submission_models.py
- exercise/templates/exercise/staff/results.html
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
**What?**
This commit adds separate resultsdata query which ignores last-only grading rule in exercises. This query is used by default in all results view and the previous query can be enabled with a checkbox.
**Why?**
Previously used resultsdata query was very slow so a new one was made that is much faster
**How?**
Previous resultsdata contained a certain case which made the query very slow. New one is basically the same without the slow part.
Fixes #918 
**What type of test …
> Add improvements to resultsdata db query

- edit_course/templates/edit_course/batch_assess.html
- edit_course/views.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
**What?**
Clarify the batch assess instructions.
**Why?**
Previously, it was not clear where the assignment IDs can be found.
The instructions now explain two different methods for fetching the assignment IDs.
Fixes #1024
Tested that the new link to the course exercises API works.
> Clarify the batch assess instructions

- lib/remote_page.py
Previously the code fixing relative URLs pointing to static content
assumed that they are located on grader server. These days the
static content is on Gitmanager, so the URLs should be fixed
accordingly.
Closes #974.
**What?**
As described in commit message. Am I thinking too simply about this? Assuming that GITMANAGER_URL only specifies the scheme and network location, as comment in recent commit by Jimmy suggests.
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
Fixes #974 …
> Changes to relative URLs on static content

- aplus/celery.py
Previously automatic SIS enrolling started only at the course
start time, but some teachers would like to see the participants
already before the start of the course.
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up your git commit history …
> Start SISU enrolling 14 days prior to course start

- edit_course/course_forms.py
- edit_course/views.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
**What?**
Clarify the instructions related to course instance cloning based on teacher feedback.
**Why?**
Teacher gave good feedback.
**How?**
See the changes to the code.
Fixes #1055
Tested that the new info notifications appear.
> Clarify course instance cloning instructions

- aplus/celery.py
- aplus/settings.py
- course/templatetags/base.py
- exercise/admin.py
- exercise/submission_models.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
Sometimes it happens that a grading job never completes because of
some technical issue, and it remains in "In Grading" state until
user submits it for regrading. This commit implements automatic
regrading of grading jobs that have not completed within configured
timeout. There is also a simple heuristic to limit the
(likely unsuccesful) automatic retries when it seems that the
grader is more persistently unavailable.
Closes #988.
**What?**
As described it commit message. There was some earlier discussion on whether the pending submission tracking should be part of Submissions table or a separate table, but my thinking is that separate table is better. Submission table is large, so it would be more inefficient to operate. Also a separate table is more convenient to handle in the admin …
> Automatic retries of incomplete grading jobs

- course/viewbase.py
Edit: this description does not match the updated version after the discussion.
Views deriving from CourseInstanceBaseMixin use self.redirect which is not defined. To fix this, This change defines self.redirect() which is equal to django.shortcuts.redirect
Fixes #1074
**What?**
This change defines self.redirect in CourseInstanceBaseMixin.
**Why?**
Multiple views were getting errors from self.redirect being undefined. All these views derive from CourseInstanceBaseMixin. 
**How?**
self.redirect is set to django.shortcuts.redirect
Fixes #1074 
* How to [test …
> Fix crash: use redirect instead of self.redirect in CourseInstanceMixin

- exercise/templates/exercise/staff/_late_submission_approval_modal.html
Fix _late_submission_approval_modal.html sending the user profile ID and not the user ID which leads to SubmissionApprovalByModuleView trying to approve submissions of a different user.
Fixes #1086
**What?**
In production, approving late submissions by module did not approve anything.
https://user-images.githubusercontent.com/46625399/192710311-f6485c59-4c9b-4b49-a784-2ffc95692b35.mp4
**Why?**
This feature saves a lot of work from teachers, and this fix also prevents the wrong user's submissions from being modified.
**How?**
Instead of sending the user profile ID in the post request, we instead send the user ID which is what the view uses.
Fixes #1086 
* How to [test your changes in …
> Fix approve late submission by module

- exercise/protocol/exercise_page.py
- exercise/submission_models.py
- exercise/templates/exercise/submission.html
- exercise/templates/exercise/submission_plain.html
- exercise/views.py
**What?**
Fix extra submission form appearing in delayed feedback with file submit exercises.
This PR also changes ``submission.html``to use tabs instead of spaces for indentation, as is agreed with the A+ style guide.
**Why?**
This issue was reported by a teacher.
The extra form along with its file input and submit-button was confusing to students and could lead to wasted submissions.
**How?**
File submit exercises no longer show the exercise instructions along with the file input field and submit-button in the delayed feedback before the feedback is given.
Fixes #935
Tested that delayed feedback no longer has the confusing layout in the submission modal or plain submission page.
> Fix extra submission form in delayed feedback

- lib/email_messages.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
- news/forms.py
- news/views.py
Adds checkbox to Edit news view to request sending email.
Closes #377.
**What?**
As described above. Tested locally using MailHog as mail server, to internal/external student audiences.
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up your git commit history before …
> Option to send email to students about news items

- aplus/celery.py
- course/templatetags/base.py
- exercise/submission_models.py
Pull request #1035 had some fundamental errors that got unnoticed at the time.
**What?**
As discussed in the commentary of the above-mentioned pull request.
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up your git commit history before submitting the pull …
> Fix errors in automatic grading retries

- aplus/celery.py
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
> Fix double definition of Celery setup_periodic_tasks

- course/api/views.py
- course/models.py
- edit_course/management/commands/reload_course_configuration.py
- edit_course/operations/configure.py
- edit_course/operations/tests.py
- edit_course/templates/edit_course/edit_content.html
- edit_course/views.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
**What?**
Optimizes database access in course configuring.
Adds simple unit tests to test the course structure after configure call.
**Why?**
Course configuring has been extremely slow.
**How?**
By fetching objects in a single query and only updating objects that have changes.
> Optimize course configuring

- doc/jenkins/README.md
- requirements_testing.txt
- selenium_test/run_servers_and_tests.sh
- selenium_test/test/test_initializer.py
**What?**
Replace nosetests with unittest.
**Why?**
#1030 
**How?**
Remove XML output from selenium tests and use unittest instead of nosetests.
Closes #1030
Checked that the tests are still run correctly (and pass).
> Replace nosetests with unittest + small selenium change

- lib/email_messages.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
- news/forms.py
- news/views.py
**What?**
Adds a checbox to edit news form so that the news contents can be emailed to course staff (in addition to course's students).
**Why?**
Requested by a teacher.
**How?**
Adds new checkbox to edit news form. Updates email sending logic to combine student and staff email addresses.
Fixes #1170
When querying which email addresses the news contents should be sent to, tested that all checkbox combinations returned the correct address list. …
> Add possibility to email course news to course staff

- assets/js/aplus.js
- exercise/templates/exercise/exercise_plain.html
- exercise/templates/exercise/submission_plain.html
- templates/base.html
**What?**
Highlight.js may automatically detect the programming language whose syntax is highlighted, but the latest version of highlight.js fails to detect the language correctly more often than expected.
This fix sets the language manually based on the URL file extension. If the URL does not end with a file extension or highlight.js does not know the file extension, the language is detected automatically.
Matlab and Dockerfile language detection is not included in highlight.js by default, so language support for those was also added.
Fixes #1221
Tested that the programming language is now highlighted correctly in previously incorrectly highlighted code, including Python, Matlab, and Dockerfiles.
**Think of what is …
> Set programming language manually for highlight.js

- deviations/templates/deviations/list_dl.html
- deviations/templates/deviations/list_submissions.html
- deviations/templates/deviations/override_dl.html
- deviations/templates/deviations/override_submissions.html
- deviations/tests.py
- deviations/viewbase.py
Fix column granter and time not being visible when the deadline deviation applies to multiple exercises for the same user
Fixes #1046 
**What?**
Fix not being able to see the granter and grant time when multiple exercise have deviations (at least this is how I understood it, my Finnish isn't as good as my English).
**Why?**
This is important metadata which should always be visible.
**How?**
I copied these lines:
https://github.com/apluslms/a-plus/blob/20d2ed61beb0b8201746f8e374374cefef0c36f5/deviations/templates/deviations/list_dl.html#L126-L139
And then replaced deviation with deviations.0 and replaced the empty `<td>` tags with this.
Fixes #1046 
* How to [test your changes in …
> Add column granter and time when multiple for same user

- assets/js/participants.js
**What?**
The additional space resulted in the emails being copied as "%20email@aalto.fi" instead of just "email@aalto.fi"
**Why?**
Typo
**How?**
By fixing the typo
> Fix the mailto link

- course/models.py
enroll_student method enrolled a users as student even if they were already enrolled as assistant or teacher.
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
> Do not re-enroll course staff as student

- edit_course/operations/configure.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
**What?**
Adds support to import new course module settings from gitmanager: model answer and model solution reveal rule.
See https://github.com/apluslms/a-plus/pull/1229.
Related pull requests:
- https://github.com/apluslms/a-plus-rst-tools/pull/168
- https://github.com/apluslms/gitmanager/pull/51
**Why?**
Options should be able to be configured in the courses' repositories.
**How?**
Check the new module attributes.
Added rst code to O1 and Aplus manual repositories that configure new course module options. Ran gitmanager and A+ locally and checked in A+ course settings that the options were saved.
*Clean up your git commit history before submitting …
> Add support to import module model solution from gitmanager

- course/templates/course/_siblings.html
- course/views.py
- edit_course/course_forms.py
Fixes #1266
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
> Fix non-revealed chapters in ModuleView

- course/permissions.py
- lti_tool/templates/lti_tool/_siblings.html
- lti_tool/templates/lti_tool/lti_course.html
- lti_tool/templates/lti_tool/lti_exercise.html
- lti_tool/templates/lti_tool/lti_module.html
- lti_tool/utils.py
- lti_tool/views.py
**What?**
This builds on pull request #1275 , and is made against the 1.20 branch. In other words, #1275 should be checked first.
I ended up doing a dedicated _siblings.html template for LTI tool, because the logic is slightly different than in the original one (this supports also the case where LTI is limited to a single module, in which case it will not be possible to navigate to Course content TOC or other modules.)
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+req …
> Make navigation links visible in LTI tool

- course/templates/course/_siblings.html
- exercise/cache/hierarchy.py
- exercise/viewbase.py
**What?**
This is similar fix than in PR #1290 for 1.20 branch, but made against current master. The cache hierarchy was heavily refactored since 1.20 was released, so the fix needed to be rethought for the new code.
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up …
> Cache iteration fix

- edit_course/course_forms.py
Fixes #1201
**What?**
Setting a non-unique CourseInstance.url in the edit course instance form crashes the application.
**Why?**
The non-unique url was throwing an error and was not being properly validated.
**How?**
The non unique url is now properly being validated to see the outcome that it already exists.
**Think of what is affected by these changes and could …
> Setting a non-unique CourseInstance.url in the edit course instance form crashes

- edit_course/views.py
Fixes #1327
**What?**
Setting a unique CourseInstance.url in the edit course instance form crashes A+
**Why?**
When editing the url to a unique value and saving the changes, the page crashes as the old url is being called, which no longer exits.
**How?**
Changing the code so the it calls the new url being saved.
**Think of what is affected by these changes and …
> Setting a unique CourseInstance.url in the edit course instance form crashes A+

- userprofile/api/full_serializers.py
- userprofile/api/tests.py
**What?**
Added a datapoint to the detailed user data in the A+ api. Allows the admin to see which courses the user is a teacher in. 
**Why?**
Change needed to create automatic A+ mailing list. 
**How?**
Added data to api which fetches the courses where the user is staff.
Tested to see that the data shows up in the api.
*Clean up your git …
> Add courses where user is teacher to api

- course/models.py
- edit_course/course_forms.py
Fixes #782
**What?**
When editing a course instance, if one used 'instances' as the URL, it did not get saved into the database due to being a reserved word, but the returned HTML still contained the broken path for all links on the page.
**Why?**
The URL was only checked for disallowed strings on the model level, which is only run after the URL validation process. This caused the links in the returned HTML to contain the broken URL, as no ValidationErrors were raised.
**How?**
A test similar to the one on the model level was added to the URL validation (CourseInstanceForm -> clean_url). Also a static class variable RESERVED_URLS was added to the CourseInstance class, so the forbidden strings list can be referenced from the CourseInstanceForm class without being redeclared in multiple …
> Fix course instance editor breaking when using "instances" as URL.

- exercise/templates/exercise/_user_results.html
Fixes #1248
**What?**
Course staff does not have a link to a unrevealed module answer chapter
**Why?**
The course front page will show black text instead of a link for an unrevealed chapter
**How?**
A fix has been added that if course staff is checking the points page then they should see the unrevealed chapters through early access.
**Think of what is affected …
> Course staff does not have a link to a unrevealed module answer chapter

- course/api/full_serializers.py
**What?**
Adds the course image to the API.
**Why?**
We are planning to show the course image in the IntelliJ plugin, so I made it easier to access.
**How?**
Adds the image field to the CourseSerializer.
- Tested the API with no course image, which returns "image": null
- Tested a course with an image, which returned "image": "http://localhost:8000/media/public/course_instance_1/O12024Thumbnail.png"
**Think of …
> Add the course image to the API

- course/templates/course/course.html
- exercise/static/exercise/chapter.js
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
Fixes #1140
**What?**
Add alert reminding users where they left off (if they have viewed a chapter before)
**Why?**
Users might forget where they were, so this provides convenient navigation
**How?**
Set a local storage value in `AplusChapter` `init` function in `chapter.js` which contains the URL and title of the page. In the landing page, check if the local storage value exists, in which case we display a link with the title in an alert box.
Fixes #1140
**What type of test did …
> Add last chapter reminder and link to index.html

- course/api/views.py
**What?**
Add module opening and closing times to API
**Why?**
Requested for the needs of the Aalto Grades project
Fixes #1361
> Add module opening and closing times to API

- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
**What?**
Add missing translations regarding submission tags to the clone course instance view
**Why?**
The translations were missing
**How?**
Added translations to django.po files
Checked that the translations worked and were correct
> Add missing translations to clone course instance view

- course/templates/course/_course_menu.html
**What?**
Move the pseudonymization button from the teacher menu to the teaching assistant menu to allow TAs to also use the button. 
Fixes #1376
> Fix pseudonymization not showing up for TAs

- external_services/templates/external_services/list_menu.html
**What?**
The group column is empty all the time.
Related issue: #1410
**Why?**
The cause of the bug is the incosistency of the name of a parameter between in `/a-plus/external_services/templates/external_services/list_menu.html` and in `/a-plus/external_services/forms.py`
**How?**
I corrected the parameter passing in `/a-plus/external_services/templates/external_services/list_menu.html`
Now the group labels are correctly displayed. `None` is displayed if the group label is not defined in the creation.
Fixes #1410 
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check …
> Fix: group labels are not shown in Edit_Course/Menu page

- exercise/staff_views.py
- exercise/templates/exercise/staff/inspect_submission.html
- exercise/tests.py
**What?**
NextUnassessedSubmitterView did not always manage to find all unassessed submitters.
The new simplified code fixes this.
Fixes #1412
Tested locally that the new code works.
> Fix NextUnassessedSubmitterView

- course/long_urls.py
- course/templates/course/_course_menu.html
- course/templates/course/staff/all_submissions_table.html
- course/viewbase.py
- course/views.py
**What?**
Added a view for viewing all the submissions within a course, with tag filtering enabled
https://github.com/user-attachments/assets/a99c9d9a-afb8-4e7e-a31e-d37d63a8f960
**Why?**
It is a highly required feature.
**How?**
Add and linked`AllSubmissionsView` and `all_exercise_submissions.html`
Fixes #1408 
**Think of what is affected by these changes and …
> Feature: add a view for all the submissions within a course

- exercise/api/views.py
**What?**
Add more detailed 404 and 403 error messages to the points API.
**Why?**
Error 404 `Not found` was returned, when the course ID did not exist or when the student was not enrolled.
This was sometimes confusing.
Fixes #876
> Add more detailed error messages to the points API

- exercise/views.py
- Personalized points goal checks that the goal is more than the required points for a module. However this happens AFTER the points goal is saved. This fixes that
**What?**
Prevent the creation of points goals that are below the required amount of points for a module
**Why?**
Not good UX
**How?**
Return out of the code that saves a points goal before the points goal is created or updated
**Did …
> Fix small bug with personalized points goal

- assets/js/table.js
- deviations/static/deviations/filter_deviations_by_submitter.js
- deviations/templates/deviations/list_dl.html
- exercise/templates/exercise/staff/user_results.html
**What?**
[[ANSWER HERE]](https://github.com/apluslms/a-plus/issues/1458)
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
Fixes #1458
> Added deadline deviation in student view

- exercise/views.py
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
https://github.com/apluslms/a-plus/issues/1466
> Fixes issue: Exercise questionnaire not displayed after grader service downtime despite successful submission
