apluslms/a-plus

api_urls.py, course/admin.py, course/migrations/0005_auto__add_coursehook.py, course/models.py, doc/example_grader.py, doc/initial_data.json, exercise/api.py, exercise/submission_models.py
CONTAINS SCHEMAMIGRATIONS!
Adds CourseHook that enables calls to URLs after a submission is
set as ready on a specific course instance.
SubmissionContentResource is an API resource that displays the
contents of the submitted files (if there are any) base64 encoded,
as well as, students ids.
Together these can be used to automate certaing tasks with external
services, e.g. plagiarism detection.
=> Add CourseHook that calls url and SubmissionContentResource to API

assets/css/main.css, templates/course/view_instance.html
With this modification, the exercise buttons in the main view are narrower if there are more than 10 exercises in one exercise round. This prevents some layout issues.
=> Make exercise buttons narrower if there is a lot of exercises

django_shibboleth/views.py
Fixes a problem where A+ fails when user has no email set in Shibboleth
attributes. These cases occur at least when students have study rights for
individual courses (erillisopinto-oikeus).
=> Hotfix problem that occurs when user has no email field set in Shibboleth

assets/css/main.css, exercise/templates/exercise/_user_results.html
Emphasizes the categories better in cases when there are multiple categories. See the image.
=> Emphasize categories better

assets/css/main.css, assets/js/aplus.js
When viewing a submission in staff view in the modal panel, copying the code copies also the line numbers. This small tweak prevents this.
The CSS is based on a example in https://developer.mozilla.org/en-US/docs/Web/CSS/user-select
=> Prevent copying line numbers in code preview

api/urls_v2.py, course/api/serializers.py, course/api/views.py, exercise/exercise_models.py, exercise/staff_views.py, exercise/views.py, lib/api.py, requirements.txt, userprofile/api/serializers.py, userprofile/api/tests.py, userprofile/api/views.py
Implementation of api resource courses for api v2.
For now we use development version of drf-extensions as the nested routes is not yet merged to upstream. I expect this to be done, before we hit production or it should be copied to a-plus repo.
There is no links to exercise resource as it's not present in this branch.
=> Feature: api courses resource

api/urls_v2.py, aplus/settings.py, course/api/full_serializers.py, course/api/serializers.py, course/api/views.py, exercise/api/full_serializers.py, exercise/api/serializers.py, exercise/api/tests.py, exercise/api/views.py, exercise/async_views.py, exercise/submission_models.py, exercise/templatetags/exercise.py, exercise/tests.py, lib/api/constants.py, lib/api/core.py, lib/api/mixins.py, lib/api/serializers.py, requirements.txt, userprofile/api/full_serializers.py, userprofile/api/serializers.py, userprofile/api/tests.py, userprofile/api/views.py
A lot of changes to API v2 backend. It should be now more mature and have better structure for future development. Set of helpers are under `lib/api`. 
Files `serializers.py` have only brief and similar serializers that **do not** depend on other serializers. Files `full_serializers.py` can include brief serializers from other modules/apps. This pattern is used so we don't end up with cyclic imports.
Important changes to work in progress api urls:
* `course_id` and `user_id` fields are now just `id` as all aplus objects returned by the api _should_ include `id` and `url` fields. `id` can be missing for objects that are virtual (e.g. `submissions/<id>/grading`)
* User detail field `courses` is renamed to `enrolled_courses`
* `exercises/<id>/submissions/<id>` is changed to …
=> Feature: api rework

external_services/lti.py, external_services/migrations/0006_ltiservice_enable_api_access.py, external_services/models.py, external_services/templates/external_services/lti_form.html, external_services/views.py
Adds 3 custom parameters into lti launch parameters. This contain course api url, course id (for db lookup without api url parsing or request) and users api token.
In future this api token should be created per service (allows revoking access to one service).
This patch is required for mooc-jutut.
=> Feature: api token in lti laucnh request

assets/js/aplus.js, templates/base.html
Allows easy copying of students' code in Inspect view.
The button text cannot be currently translated and this does not work with model solutions.
=> Implement Copy to clipboard button

assets/js/aplus.js
The invisible `textarea` was placed at the end of the text to be copied. Therefore, clicking the copy button will jump to the end, which is a bit irritating.
=> Prevent scrolling when copying to clipboard

edit_course/operations/configure.py
Since usually when you paste configure url from mooc-grader it comes with space in the end and breaks the configure phase. It has been annoying enough for me to create a simple fix, since it is less effort for the server to strip the space than me doing it manually.
=> stripped whitespace from course configure urls

edit_course/operations/configure.py
The key was changed in mooc-grader in order to fix an [issue](https://github.com/Aalto-LeTech/mooc-grader/issues/18).
=> Fix obsolete course configuration key

course/templates/course/staff/participants.html
Fixes tag checkboxes being hard to read if the background is dark.
Turns out it was caused by a trivial typo.
=> Replace tag.text_color with tag.font_color

exercise/templates/exercise/staff/analytics.html
Found the same bug in another place. There should be no more, at least
according to grep.
=> Replace tag.text_color with tag.font_color in analytics

lib/cached.py
This PR tries to solve the cache invalidation bug fix which happens when:
1. time consuming cache generation starts
2. during the generation the cache is invalidated from another uwsgi python process
3. when the generation ends the result is actually useless since new invalidation was done during the generation
The code should include enough comments to understand the fix. From limited local testing this seems to work. Below you can see some logs which were captured while making multiple submissions to same exercise in multiple tabs (the exercise in question took a couple of seconds to complete in grader).
Please look at the code and comment! :)
```
✘  ~/koodaus/work/plus-dev  ./docker-up.sh | grep "DEBUG/cached"
Starting aplus_grader_1 ... 
Starting aplus_grader_1 ... done
Starting …
```
=> Cache invalidation/generation bug fix

assets/js/aplus.js
Highlights the correct menu entry for an open page.
Removes selection based on data-type-tag, and instead selects those menu elements whose target path matches the current URL.
Tested on the live O1 2017 course with Chrome dev tools, so it should work as intended with chapter/excersise-type menu items.
=> Menu highlighting

assets/js/aplus.js
Takes into account multiple simultaneous menu items that require highlighting.
Returns data-view-tag highlighting because of special cases that require highlighting items which don't lead to the open URL.
=> Generalize menu highlighting

course/cache/students.py, course/templates/course/course_base.html, course/viewbase.py
...so that courses can customise their content based on tags.
How to use:
Suppose you have an HTML element with id 'thing-to-show' that you want
to show if the student has a tagging with the slug 'dont-show'. You should
put in your CSS file:
```css
[data-taggings~=dont-show] #thing-to-show {
display: none;
}
```
Of course, other combinations of selectors are possible, as well as reading
the attribute from JS.
=> Add data-taggings to course_base

deviations/views.py
This PR fixes a bug where in the deviation view:
1. teacher chooses exercises (not modules)
2. teacher chooses new date (not minutes)
3. system incorrectly states that the student already has a deviation on that exercise
When you look at the code please note that the previous minutes value was coming from the top of the function, thus being None in the new_date scenario.
=> Deviation bug fix

edit_course/operations/configure.py, exercise/exercise_models.py, external_services/models.py, lib/helpers.py, locale/fi/LC_MESSAGES/django.po
LTI exercises may use relative service URLs to modify the global LTI service URL and the JSON course import shows errors if the LTI service used by an exercise can not be found in A+.
**Relative service URLs in LTI exercises:**
* If an LTI exercise defines its own service URL and it is a relative URL, it is joined to the URL of the LTI service. Relative URLs with an absolute path replace the previous path completely.
* Absolute service URLs are also still supported for backwards compatibility, though their use is discouraged. The URL domain must equal the domain of the LTI service.
* If the exercise defines no service URL, the URL of the LTI service is used.
**Course import error message for missing LTI services**
LTI exercises refer to the LTI service by a label in JSON. JSON course …
=> LTI exercise relative URL and missing LTI error in course import

exercise/static/exercise/chapter.js, exercise/static/exercise/poll.js
Currently, submit buttons remain disabled in exercises embedded in chapters after the user has submitted once. The user would have to refresh the web page to be able to submit again. This PR reloads the exercise description after the submission has been graded and re-enables the submit buttons. The exercise description is reloaded because some exercises may change after submitting. Active elements are not reloaded since they contain no exercise description.
The new CustomEvents were expanded: a new event for a finished and graded submission and a new event for an aborted submission (aborted before the submission is sent anywhere).
=> Enable submit buttons and reload the exercise description after finishing a submission

exercise/exercise_models.py
Previously, enrolled teachers and assistants could not submit after exceeding the exercise max submissions limit. Now they can. This fix does not show any warnings about the submissions limit to teachers even though teachers are shown a warning about the deadline when submitting after the deadline.
=> Teachers' submissions ignore the exercise max submissions limit

aplus/local_settings.example.py, aplus/settings.py, doc/DEPLOYMENT.md, doc/nginx/aplus-nginx-shib.conf, requirements.txt, shibboleth_login/apps.py, shibboleth_login/auth_backend.py, shibboleth_login/parser.py, shibboleth_login/templates/shibboleth/meta.html, shibboleth_login/tests.py, shibboleth_login/views.py
* Dictionary style settings for shibboleth configuration
* Implement a parser for shib2 encoded multivalue fields.
* Parse only a single student number, based on a config value
* Authentication backend is rewritten, but should be more robust
and handle problems better than before.
e.g. before, oo long input values were just cut, and thus multiple
different inputs might have resulted same output.
Now we raise errors instead and require someone to fix the actual
problem.
* Better debug output.. So we can actually find out these problems :)
Note that the `SHIBBOLETH_ENVIRONMENT_VARS.STUDENT_DOMAIN` configuration variable is now required with shibboleth! Check the documentation.
=> New Shibboleth authentication

assets/js/filter.js, exercise/static/exercise/results_staff.js, exercise/templates/exercise/staff/results.html
Fix decimals to two in the indicators, currently there are about 10 decimals shown, it makes the table hard to read.
Also add option to filter to get the count of visible table rows with #selected-number ID. Currently the selected students / total students on top left of table is not shown.
=> Bug fix to EoC. Fix decimals and method to get filtered row count.

api/urls_v2.py, assets/js/tag_popover.js, course/api/views.py, course/static/course/usertagdropdown.js
Previously, deleting user taggings in the course participants page
could fail because the JS code did not handle paginated responses
from the API. The code retrieved all user taggings for the tag
even though it was only supposed to remove one tagging.
The commit adds a new endpoint to the API so that it is easy to
delete taggings without retrieving all taggings (which was
previously done to find out the ID of the tagging to delete).
The new JS code for the deletion may also delete multiple taggings
in a single HTTP DELETE request.
=> Fix JS bug in the removal of user taggings

exercise/staff_views.py
The function  `extract_form_errors` was already used in the file `staff_views.py` yet it was not imported which caused an 'undefined name' error.
=> FIX: Import a function that was already used.

exercise/cache/points.py
Even though the submission with statuses `initialized` or `waiting`
can be rejected, it is better to have them counted in the submission
count. It is more clear for the students so they can see how many
submissions they've made. If the submission gets rejected, it will be
removed from the total submission count.
Adding these statuses to the total count benefits especially exercises
that are graded manually, such as Rubyric exercises. Also not counting
those statuses could give false information of the submissions left, if the
waiting submission should pass.
Fixes #407
=> Show initialized and waiting submissions in the submission count.

exercise/templates/exercise/_user_results.html, exercise/templatetags/exercise.py, locale/fi/LC_MESSAGES/django.po
If module is open for reading, it is now opened by default in the
exercise results page. Add a badge to inform that this module is for
reading only. Add correct prepositions with dates (Opens on saturday).
Template tag `module_accessible` fixed to work properly, even when
opening time is not set.
Related issue #473
=> Show modules open in the results page, if they are open for reading

course/templates/course/module.html, course/templatetags/course.py, exercise/exercise_models.py, exercise/templates/exercise/_user_results.html, locale/fi/LC_MESSAGES/django.po
Previous version showed only the date of the deadline.
Additionally, activate the links to the exercises between the closing time and the late deadline.
Fix #382
=> Show the time of the late deadlines

edit_course/templates/edit_course/edit_content.html, edit_course/views.py, locale/fi/LC_MESSAGES/django.po
The exercises and chapters are now separated in the Edit course page.
Fixes the previous implementation of  the `is_submittable` function in the template.
Related issue #477
=> Separate chapters and exercises in the Edit course page

course/permissions.py, course/views.py, exercise/exercise_models.py, exercise/tests.py, locale/fi/LC_MESSAGES/django.po
If course has a enrollment exercise, the exercise can be answered even
if the module containing the exercise was closed.
Additionally add a dot in the end of sentence.
=> Enrollment questions are open after module's closing time

api/urls_v2.py, course/api/full_serializers.py, course/api/serializers.py, course/api/views.py, course/permissions.py, exercise/api/views.py, exercise/exercise_models.py, exercise/protocol/aplus.py, exercise/staff_views.py, exercise/views.py, locale/fi/LC_MESSAGES/django.po, userprofile/api/serializers.py
Add API endpoints for retrieving StudentGroups and for submitting new solutions to grading. Both endpoints can be accessed by students. These are needed by the new IntelliJ IDEA plugin.
No unit tests have been added. I tested the API endpoints manually with curl or in the web browser. My testing covered different error cases and access control for users (teachers and students).
Manual testing needs to check that normal submissions still work (in the normal course web page). The old grade function was slightly changed so that the API requests are not dependent on the session-based Django messages framework.
No, the API has not previously been documented like that and won't be now either.
=> Group and submission API endpoints

course/templates/course/groups.html
The groups.html -template had a div-tag that was missing its end tag. This commit adds that missing end tag.
All unit tests of the project except the broken test pass.
=> Add missing html end tag to a template

aplus/settings.py, locale/fi/LC_MESSAGES/django.po, userprofile/static/userprofile/extra_logins.js, userprofile/static/userprofile/login.css, userprofile/templates/userprofile/login.html, userprofile/views.py
- The local user login (previously "maintenance login") is rarely used, yet was visible on the login page. This pull request hides that login option by default if there are normal login options and provides support for hiding other additional login options similarly. These hidden login options can be made visible by pressing a button.
- The "Maintenance login" was quite unclear and misleadingly named, the title is changed to a more fitting "Local users" and an instructive and descriptive text is added to explain who should use the login in question.
- The texts for the local user login used to be fetched from aplus/settings.py, this changes the implementation to hard coding by defining the login texts directly in the template.
- The texts in the login box headings and login buttons were …
=> Improve extra login options on login page

external_services/lti.py
Remove all uses of `request.get_host()` and use `settings.BASE_URL` instead. 
This is safer because BASE_URL is defined in the settings while get_host() comes from the users' browser which allows it to be manipulated by the user.
Fixes #422
All the URLs that are now calculated using `BASE_URL` have been checked to render the same result as before with `get_host()`.
Not relevant
=> Replace get_host() with BASE_URL

aplus/local_settings.example.py, aplus/settings.py, external_services/lti.py
This PR changes how  `tool_consumer_instance_name` is set and adds two new parameters: 
`tool_consumer_instance_description` and  `tool_consumer_instance_url`. Setting the the instance name using BRAND_NAME enables easier branding.
Testing has been done manually with the help of https://github.com/Aalto-LeTech/django-lti-login
Not relevant.
=> LTI: enable branding for instance name Fixes #423

doc/DEPLOYMENT.md, exercise/cache/exercise.py, requirements.txt
- Exercise and chapter pages are stored in the cache and only update if the backend reports that there is a change. Some pages might be too large to fit in the cache (e.g. 1M), but do compress relatively well. Memcached API supports compression on the fly, but that is not usable over django API. This pull request adds lz4 compressor (https://pypi.org/project/lz4/) and zlib as backup (https://docs.python.org/3/library/zlib.html) to compress HTML exercise and chapter pages so that they can be stored in the cache, and decompress them before viewing.
- Compress and decompress functions can be changed easily by modifying the corresponding global variables in exercise.py.
Fixes #510 
- The existing unit tests pass, I have not added new unit tests.
- Testing can be done manually by checking that …
=> Compress HTML pages in cache

assets/css/main.css, course/templates/course/_course_menu.html, course/templates/course/course_base.html, locale/fi/LC_MESSAGES/django.po, templates/base.html
Adds two skip links - one at the top of the page which jumps
to the page contents, and another at the top of the "course menu"
which jumps to the course content.
As described in https://github.com/apluslms/a-plus/issues/559 this is really useful for keyboard users.
It would be sensible to merge this after #547 , as it doesn't have it's own focus state.
Here are a couple of screenshots of how it looks on top of the focus state from #547:
Fixes https://github.com/apluslms/a-plus/issues/559
I've not tried any changes to the automatic tests for keyboard-only stuff here.
It can be tested manually by tabbing through the pages, and especially pages where the course menu is visible. 
I don't think it's necessary to add any specific documentation here.
=> Create "skip links" for keyboard users

locale/fi/LC_MESSAGES/django.po, userprofile/static/userprofile/extra_logins.js, userprofile/templates/userprofile/login.html
Add labels to local user login form to support accessibility and fulfill accessibility standards. By switching the login form to use the Django form, also error messages and error handling are provided automatically.
Also change color of the login button to make it look more like a button.
Fixes #582 
All existing unit tests pass (except the one broken one)
Manual tests:
- Works with keyboard navigation
- Works both in English and Finnish
- Works with a screen reader
=> Add labels for local user login form

course/models.py
Show all modules to course teachers and assistants in API endpoint
`/api/v2/courses/ID/exercises/`even if not open yet.
Previously unopened modules were hidden from everyone instead of only
students.
Fixes #549 
API endpoint has been tested for all user types.
Not relevant
=> Show all modules to course teachers and assistants in API endpoint

assets/css/main.css, course/templates/course/_course_cards.html, course/templates/course/index.html, locale/fi/LC_MESSAGES/django.po
In order to better accommodate longer course and course instance -names, the bootstrap3 row-column-grid is removed from front page sections and flex-box is applied instead. This enables the course cards to grow vertically.
Four media-breakpoints have been applied, so that the width of the cards would look good with different screens.
The second commit 57e54963a is only to fix the indendation of the adverts, so that the changes made in the first commit can be more easily spotted.
Fixes #583
**Desktop width**
**Tablet width**
**Mobile width**
- The appearance after changes has been tested on Chrome and Firefox and different screen widths.
- The appearance has also been tested with Lambdatest on Edge and IE. 
- It has also been tested for very long and very short course and course instance …
=> Front page flex-box

course/templates/course/_course_menu.html, course/templates/course/_siblings.html, course/templates/course/course_base.html, locale/fi/LC_MESSAGES/django.po, templates/base.html
The previous audit highlighted that we have very few landmark roles in use. These are useful for giving semantic strucutre to the page and some assistive technology users will use them to "jump" from element to element around the page (similar to the skip links). 
One particular challenge here was that we need `main` to include the content. On all non-course pages, that's everything after the main navigation, but on course pages it starts after the course navigation. For this reason, there's an optional block which can be defined to override the usual `<main>` tag, for example, with a semantic-free `<div>` or any other element as needed. This is currently only defined for the course template. 
Fixes #595 
If you're not familiar with landmarks, I suggest starting with [W3Cs example …
=> Add landmark roles to the template

selenium_test/test/locators.py
One of the items on BasePageLocators referenced to a `<nav>`, which
had been replaced by a `<div>` in https://github.com/apluslms/a-plus/commit/426a0c727c5b718754c0e48d8d4aecdc1028bd45. It broke the selenium-tests. This fixes that.
All selenium-tests and unit-tests pass now.
Not relevant 
- [x ] I (developer) have tested the changes manually
=> Fix the broken selenium-test-locator

exercise/exercise_models.py, locale/fi/LC_MESSAGES/django.po
Return an error message if POST data contains invalid JSON, when
getting group id in `_check_submission_allowed`.
Earlier this error was silently ignored, meaning that a user would
have gotten an error about how something is wrong with their group,
when it's really caused by a syntax error in the data.
Fixes #613
Changes have been manually tested.
Not relevant
=> Handle invalid JSON in check_submission_allowed

exercise/api/custom_serializers.py, exercise/api/full_serializers.py, exercise/api/serializers.py
Move `max_submissions` and `max_points` from `ExerciseSerializer` to `BriefExerciseSerializer`. 
Fixes #605 
API endpoints have been manually tested
Not relevant
=> Move max submissions to BriefExerciseSerializer

assets/css/main.css, course/templates/course/_enroll_form.html, course/templates/course/course_base.html, course/views.py, locale/fi/LC_MESSAGES/django.po
- If the course instance has ended and enrolling has already closed, the page visitor will be told that the course has already ended. 
- If there is an instance of the same course, that has a later ending time than now, and that instance is visible for that user, they will be given a link to that instance. 
- If there are several instances that fit this description, the latest is given.
- Even if the course has already ended, but the enrolling would for some reason be open, the enroll_form is shown.  
- Front page and enroll-page of the course show the link to the latest instance of the course. 
- Other course-pages show only the text "This course has already ended" to save some database-queries
(If the link is wanted for other pages as well, most likely the best option would be to move …
=> Past instance notification

course/models.py, exercise/exercise_models.py, exercise/submission_models.py
Save language to submission `meta_data` even if not provided. This way the language 
is consistent when regrading a submission where language data isn't given.
Fixes #611
Changes have been tested manually.
Not relevant.
=> Save language in submission even if not provided

README.md
Mention of media-folder is removed from `README.md` as it is not being used for any permanent data storage.
All existing unit- and selenium-tests pass
This will make README to be up-to-date
=> Remove mention of media-folder from README.md

course/templates/course/_siblings.html
It's a little annoying when listening to pages with VoiceOver that the "double angled quotation marks" in the pagination navigation area get read out. 
Since they're mostly decorative (it's possible to tell, as we're inside a `nav` called "pagingation", that these will be the next and last pages), they are hidden from assistive technology as a whole. 
Tested manually with VoiceOver
=> Wrap "double angle quotation marks" in aria-hidden

assets/js/aplus.js, authorization/exceptions.py, course/exceptions.py, course/viewbase.py, course/views.py, lib/helpers.py, lib/middleware.py, locale/fi/LC_MESSAGES/django.po, templates/404.html, userprofile/views.py
This PR adds a possibility of linking to a specific page in A+ in a specific language or viewing content with different language without having to change and save it in profile or in course page, by using language query parameter at the end of the url. 
For example, adding ?hl=en at the end of the url changes the content to English if it's supported for the page. If not, an error is raised.
* If the language is supported for A+ but not for this course, a 404 html page is shown with a list of available languages and links for each.
* If the language is not supported for A+ at all, a 404 page is shown with a link to the material in default language.
Language parameter stays in the url when navigating through page, except when user changes language either on course page
or on profile page. …
=> Change language based on query parameter

templates/accessibility_issues_en.html, templates/accessibility_issues_fi.html
This adds a statement to the system-level accessibility statement noting that teachers may break accessibility of courses, and that other institutions using A+ may make their own customisations. 
Once we are agreed on some text, if someone wants to add a Finnish version, I'd be happy to add it here. 
This only changes a tiny bit of text. 
=> Add teacher disclaimer to accessibility statement

exercise/templates/exercise/_user_results.html, exercise/templates/exercise/exercise_base.html, exercise/templates/exercise/exercise_plain.html
The dropdown menu that shows the student submissions use a `a` tag instead of a button. Therefore, we need to add some semantics to that tag. Maybe a better solution could be to use a button instead but adding some aria attributes also solve the problem.
Fixes #597 
I tested the changes manually using [Chromevox](https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en)
There is no need to update any documentation.
=> Add aria support to anchor tags that list student submissions

course/migrations/0047_enrollment_language.py, course/migrations/0048_delete_duplicate_enrollments.py
The current production and test servers in Aalto were previously migrated to the for-o1-2020 hotfix branch. After said branch was merged in 32b86bf17a33a5c001cc4a3ac87c41b50d8e4100 the migrations were ordered incorrectly and could not applied to the database. This pull request fixes the order of the migrations in such a way that they can be successfully applied both to the existing databases as well as an empty database.
The changes have been tested on a database dump taken from the production A+ in Aalto, as well as on a blank database.
**Note**: If the migrations have been run on a new database before these changes, the migrations will fail after applying these changes. Running `python3 manage.py migrate --fake` will successfully mark the renamed migrations as applied. I believe that is …
=> Reorder migrations

assets/js/aplus.js, exercise/templates/exercise/_file_link.html
This is a hotfix to solve some of the issues that have been caused for the JavaScript code added in the commit 2b5c311. However, I recommend working in the Pull Request #736 in order to allow the users to navigate the course content while using the `?hl=` query parameter.
Fixe #732
Fixes #745
I tested the changes manually. I tested with some chapters of the O1 course and also the aplus manual.
=> Hotfix january modal window and event handler for the <a> tags

exercise/templates/exercise/exercise_plain.html, locale/fi/LC_MESSAGES/django.po
Aplus does not support keyboard navigation for modal windows, and all
the current exercises use modal windows for different tasks, e.g., show
model response, inspect submission among other tasks. Therefore, the
exercises must be opened in full-page for users who use keyboard
navigation. We added hidden links that are shown only when the user
navigates the course with the keyboard.
Fixes #669
I tested the changes manually.
There is no documentation related to this issue.
=> Add a hidden link to open exercises in a new tab / full-page

assets/js/buttons_popover.js
Bootstrap 3.4 (used in a-plus 1.8) introduced a new sanitize option that is used in popovers. Injecting buttons as html was prevented by this change, so the tag popovers in the Participants page (at least) only showed the title. This is a quick fix only, later on it should investigated if using a proper whitelist is necessary to limit the elements that can be injected (see https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer).
=> Fix tag popover buttons not showing due to new Bootstrap sanitize option

course/models.py, external_services/lti.py, locale/fi/LC_MESSAGES/django.po
Relies on the uniqueness of enrollments based on (course_instance, user_profile).
Requires exception handling for nonexisting entries.
Fixes #600.
Getting familiar with PR process by taking an old easy issue for fixing.
Note two inline question comments in code (i.e., this is not final PR):
1) forms.py is not affected by this issue (different query attributes), right?
2) In lti.py, should we still raise PermissionDenied exception in negative case or is the default raised by get method ok (ObjectDoesNotExist)? I couldn't yet figure out how to test lti.py
I think these were the only places in code affected by this issue (did a recursive search for enrollment using grep). Am I correct?
Fixes #600
Tested models.py in both succesful and nonexisting case.
Couldn't yet figure out how to test …
=> Change enrollment checks to use QuerySet get method.

aplus/settings.py, aplus/urls.py, course/models.py, course/sitemaps.py, course/templates/course/course_base.html, course/templatetags/base.py, exercise/sitemaps.py, templates/base.html, userprofile/sitemaps.py
**What?**
Implement the `sitemap.xml` endpoint to A+ (see https://www.sitemaps.org/protocol.html for specification). Additionally, link between alternate language versions of a page in the `<head>` element.
**Why?**
Should improve results in Google search, and also provide a way for Google to be able to serve the correct localization of a course based on the user's language preferences.
**How?**
Added `django.contrib.sitemaps` to the installed components, and the path to `sitemap.xml` in the main `urls.py` file. Each module with public content (course, exercise, userprofile) has its own `sitemaps.py` file, which defines the URLs that should appear in the combined sitemap. For courses (and models related to courses), only the ones that are public and have already started are listed in the …
=> Implemented sitemap. Fixes #520

api/urls_v2.py, course/api/full_serializers.py, course/api/views.py, exercise/api/full_serializers.py
**What?**
Add new exercise tree endpoint (`/api/v2/courses/{course_id}/tree`) to A+ API. The new endpoint presents the learning objects of a course in a tree-like hierarchy, unlike the regular `exercises` endpoint, which presents them as a flat list.
**Why?**
The flat exercise list does not sort the exercises in the hierarchical order. This new endpoint is also necessary for the IntelliJ plugin.
**How?**
Created a new viewset (`CourseExerciseTreeViewSet`) which accesses the cached content of the course instance, and two new serializers for outputting the data (`TreeCourseModuleSerializer`, `TreeExerciseSerializer`). The viewset doesn't derive from `ReadOnlyModelViewSet` and the serializers don't inherit from `AplusModelSerializer` because they don't operate on model objects. Instead, they …
=> Implement new exercise tree endpoint. Fixes #603

api/urls_v2.py, assets/js-translations/teacher.fi.json, course/api/full_serializers.py, exercise/api/csv/aggregate_points.py, exercise/api/csv/views.py, exercise/api/serializers.py, exercise/static/exercise/css/results_staff.css, exercise/static/exercise/results_staff.js, exercise/templates/exercise/staff/results.html, locale/fi/LC_MESSAGES/django.po
This is a complete rewrite of the All results page (JavaScript parts mostly). It also adds 'difficulty' field to ExerciseBriefSerializer, and defines a new API endpoint based on the old csv endpoint aggregate_points.py. I have tried to keep the existing functionality wherever possible, even though the page works very differently now.
This implementation fetches exercises, usertags, and student points by only three ajax calls regardless of the student count, and loads the results into a DataTable object (https://www.datatables.net/). Data is reloaded only in the case when user wishes to changing from official to unofficial points view, or vice versa. Using the DataTables jQuery plugin brings new functionality like column sorting, but also makes some things more difficult. DataTables also …
=> Rewrite All results page

aplus/local_settings.example.py, aplus/settings.py, lib/api/authentication/grader.py, requirements_prod.txt
**What?**
Verification layer for grading job results submitted to A+ in a Kubernetes environment.
**Why?**
The existing authentication code for receiving grading results from mooc-grader checks whether the grader service host IP matches the IP the jobs were submitted in. In a Kubernetes environment this doesn't work, as A+ refers to mooc-grader via a service URL / IP address, which differs from mooc-grader container's internal IP address.
**How?**
The new solution adds two new global configuration flags, KUBERNETES_MODE and KUBERNETES_NAMESPACE. If KUBERNETES_MODE is set to True, instead of the previously defined authentication layer, A+ now queries the registered Kubernetes API server for mooc-grader pod IP addresses in the KUBERNETES_NAMESPACE, and checks if the request IP matches one …
=> Grader IP verification in a Kubernetes environment

assets/js-translations/teacher.fi.json, exercise/static/exercise/css/results_staff.css, exercise/static/exercise/results_staff.js, exercise/templates/exercise/staff/results.html
**What?**
Fix scrolling and layout issues (e.g. width of sticky columns) on All results page (scrolling and sticky columns don't work perfectly on small screens, but proved too difficult to fix).
Also show tooltips on summary row headers to improve ease of use. Also updated tooltip texts in the JSON-file to use the term "assignment" rather than "exercise", which will be soon changed elsewhere as well. Tooltips on row headers probably don't work on mobile devices.
**Why?**
Previously when scrolling, cells overlapped strangely and sticky cells didn't behave as wanted.
**How?**
CSS-styling; Bootstrap tooltips
Fixes #832
Fixes #845 (duplicate)
* How to [test your changes in …
=> Fix scrolling and layout issues on All results page

aplus/settings.py
**What?**
Add possibility of changing the environment variable prefix from which Django settings are read.
**Why?**
In a Kubernetes environment, k8s-injected environment variables may unintendedly be parsed as settings. Being able to change the default APLUS_ prefix into something else helps, while preserving the ability of changing settings via environment variables.
**How?**
In `settings.py`, read ENV_SETTINGS_PREFIX environment variable to use as a filter for settings to be set from environment. As an example, with environment variables
```
ENV_SETTINGS_PREFIX="TESTING_"
TESTING_DEBUG=False
```
the Django DEBUG setting would be set to `False`.
=> Add customizable environment variable setting prefix

deviations/models.py, deviations/tests.py, exercise/cache/points.py, exercise/templates/exercise/_exercise_info.html, exercise/templates/exercise/_user_results.html, exercise/templates/exercise/exercise_base.html, exercise/templates/exercise/exercise_plain.html, exercise/templates/exercise/staff/inspect_submission.html, exercise/templatetags/exercise.py, exercise/viewbase.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
This pull request adds information to the student UI about the deviations granted to the student (max submissions deviations and deadline deviations).
**Why?**
Previously, the deviations were not visible to the student.
**How?**
Max submissions deviations are now counted in places that display a submission counter in the format "X/Y" where X is the current number of submissions and Y is the maximum number of submissions.
Deadline deviations are now displayed in the "exercise info" box on the standalone exercise and submission pages. They are also displayed in the exercise frame header.
This is a re-implementation of the older pull request #398. In that PR, the deviation information was added to the `CachedStudent` cache. However, in the more recent delayed feedback update, the …
=> Display deviations in student UI

exercise/cache/points.py, exercise/staff_views.py, exercise/templates/exercise/_exercise_info.html, exercise/templates/exercise/_submission_list.html, exercise/templates/exercise/exercise_base.html, exercise/templates/exercise/exercise_plain.html, exercise/templates/exercise/submission_plain.html, exercise/templatetags/exercise.py
**What?**
`CachedPoints` was duplicated in the delayed feedback update because that was the easiest way to store revealed and unrevealed exercise results simultaneously. This PR fixes the duplication.
Additionally, the PR contains several related bug fixes:
- `InspectSubmitterView` and `NextUnassessedSubmitterView` used the student version of the cache, which means they would redirect the user to the submitter's last submission if delayed feedback was enabled, even though staff members are supposed to be able to know which submission is the best one.
- The "my submissions" list would evaluate the exercise's reveal rule for each submission separately. This was unnecessary because the result would be the same for each submission. This has been optimized.
- The cache key `best_submission` …
=> CachedPoints duplication and related fixes

exercise/viewbase.py
**What?**
In a previous update, SubmissionBaseMixin was modified to use self.profile. However, self.profile is not assigned in API views, and thus SubmissionViewSet was broken. This fix changes the code so that self.profile is not accessed and the API view now works.
**Why?**
See "What?"
**How?**
See "What?"
Tested that the submission API view now works.
**Think of what is affected by these changes and could …
=> Fix bug that broke SubmissionViewSet

deviations/forms.py, edit_course/course_forms.py, edit_course/exercise_forms.py, lib/widgets.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
This PR adds a datetime picker to all datetime fields in forms.
**Why?**
This was mentioned when discussing the deviation UI with Aalto teachers.
**How?**
A new widget, `DateTimeLocalInput`, has been added. This new widget is otherwise the same as the built-in `DateTimeInput`, except it uses the `datetime-local` HTML input type, which uses a datetime picker provided by the browser. `datetime-local` expects the initial value of the field to be in a specific format, which the widget ensures. `datetime-local` is supported in all major browsers except for IE. If the user's browser doesn't support this widget type, it uses `text` instead (which the A+ forms used before this update anyway).
* How to [test your …
=> Use datetime-local in datetime form fields

authorization/api/views.py, lib/remote_page.py
**What?**
No more 500 error on loading get-token page, and fixes the import grouping for remote_page.py.
**Why?**
500 isn't correct behaviour.
**How?**
Return 400 Bad Request instead, as it makes most sense.
=> Fix get-token 500 error and PR #937 issue 

authorization/api/views.py
**What?**
Fix crash when get-token payload has invalid dates.
**Why?**
Crash bad.
**How?**
Catch exception.
Checked that it doesn't crash anymore and works otherwise.
=> Catch ValueError in get-token payload parsing

authorization/object_permissions.py, course/permissions.py, exercise/permissions.py, lib/api/authentication/grader.py
**What?**
Fixes GraderUser permissions related to Jutut access.
**Why?**
Jutut either couldn't access exercises or it crashed A+.
**How?**
Check that the user is not a GraderUser in normal permissions, and add exercise read permission to exercise tokens.
=> Permission fixes for GraderUser

exercise/api/csv/views.py, exercise/exercise_summary.py, exercise/submission_models.py, exercise/tests.py
**What?**
This PR changes the all results table to ignore submissions in the states `WAITING` and `INITIALIZED` when determining a student's final points in an exercise, and reverts a previous change (87dae322fd9777f707db2d0279ccfd1258bf0587), which changed the chapter pages to **not** ignore submissions in those states when determining the students final points.
**Why?**
In a previous commit (87dae322fd9777f707db2d0279ccfd1258bf0587), `UserExerciseSummary` was changed to include submissions in states `WAITING` and `INITIALIZED`, to match the behaviour of the all results table (which uses `CourseResultsDataViewSet`). It was later decided that this should be the other way around: the all results table should ignore submissions in the aforementioned states, like `UserExerciseSummary` and …
=> Exclude WAITING submissions from all results table

exercise/cache/points.py, exercise/staff_views.py
**What?**
The "start manual assessment" button, as well as the "inspect" button in the submission list when grouped by submitter, would cause a 404 error if none of the chosen user's submissions were marked as `best_submission` in the points cache. This PR fixes the bug.
**Why?**
Shouldn't return 404 when there actually are submissions.
**How?**
The two views in question used the method `CachedPoints.submission_ids` to get the best submission of the chosen user. This method returned an empty list when called with `best=True` and none of the submissions were considered "best" by the points cache's logic. A new optional parameter, `fallback_to_last` has been added to the method. It ensures that *some* submission is returned even when there is no "best" submission.
**Remember to add or …
=> Fix 404 when clicking "start manual assessment"

exercise/templates/exercise/staff/_submissions_table_compact.html
**What?**
In the A+ inspect submission page, the submission list has a button "Show all submissions" under it.
The button is now hidden if all submissions are already shown.
**Why?**
The button was displayed even when all submissions were already displayed, and that is misleading or confusing for the teacher.
**How?**
Fixed the if-condition in the Django HTML template.
Fixes issue [EDIT-770](https://jira.aalto.fi/projects/EDIT/issues/EDIT-770) in JIRA.
I tested that the button is correctly shown/hidden depending on if there are hidden submissions or not.
=> Fix "show all submissions" button appear condition on inspect submission page

authorization/object_permissions.py
**What?**
This PR fixes the type hinting of the `register_jwt_accessible_class` decorator.
**Why?**
IDE type checking and autocompletion was broken for all classes that the `register_jwt_accessible_class` decorator was applied to.
**How?**
The type hinting of the `register_jwt_accessible_class` decorator has been changed to use type variables instead of relying on `Type[Any]`, to signify that the input and output types of the decorator are the same.
**What type of test did you …
=> Use type variable in JWT decorator

exercise/templates/exercise/staff/_submissions_table_compact.html
**What?**
In the A+ inspect submission page, the submission list has a button "Show all submissions" under it.
The button now correctly counts and behaves with submissions that have ERROR or REJECTED status.
**Why?**
The button's render logic did not correctly count submissions with ERROR or REJECTED statuses.
**How?**
Fixed the if-condition in the Django HTML template.
Related JIRA issue: [EDIT-770](https://jira.aalto.fi/projects/EDIT/issues/EDIT-770)
I tested that the button is correctly shown/hidden now.
=> Fix inspect page "show all submissions" button more

exercise/static/exercise/assessment.js, exercise/templates/exercise/staff/_assessment_panel.html
**What?**
Replace the dropdown menu that is used to select submitted files for viewing on the inspect page with tabs, which have the file names as titles.
**Why?**
This was requested by a teacher to reduce the amount of needed clicks to switch between files.
**How?**
Modify the related HTML and JavaScript to replace the dropdown with bootstrap nav tabs.
Fixes #920
Tested that the switching between files works correctly and that a large amount of tabs starts stacking vertically.
=> Replace inspect page submitted file dropdown with tabs

lib/remote_page.py
**What?**
Remove the HTML attribute ``id="exercise"`` when chapters and exercises are rendered in the A+ frontend.
**Why?**
HTML id attributes must be unique. However, the ``id="exercise"`` was used multiple times.
**How?**
The ``id="exercise"`` is now removed in ``remote_page.py`` when A-plus retrieves chapter and exercise HTML from the backend.
Fixes #940
Checked that the duplicate ``id="exercise"`` no longer exists.
=> Remove duplicate HTML attribute id="exercise"

exercise/submission_models.py, requirements.txt
**What?**
A+ no longer tries to render some binary files in plain text in the submitted file views.
**Why?**
A teacher noticed that this problem was causing performance issues, when large binary files were being loaded for preview.
**How?**
Binary files are now detected using a library called ``binaryornot`` instead of using ``mimetypes``. The library inspects the file contents and based on that guesses whether the file is binary or not.
Fixes #965
Checked that binary files are no longer rendered with a preview in any of the submitted file views.
=> Fix rendering of binary files in submitted file views

exercise/static/exercise/chapter.js
**What?**
This change adds the missing suffix to ``<label for="">`` attribute in active elements.
**Why?**
In active element exercises, the ``<label for="">`` attribute did not match the id of the input element and thus, clicking the label did not activate the text input like it should.
**How?**
Add the missing suffix to ``chapter.js``.
Fixes #823
Checked that clicking on the label activates the text input like it should.
Also made sure that there are no duplicate ids in the HTML.
=> Fix active elements label for attribute missing suffix

aplus/settings.py, course/sitemaps.py, exercise/sitemaps.py, exercise/templates/exercise/exercise_base.html, lib/sitemaps.py, templates/base.html
**What?**
* Improve A+ Google search sitemaps with dynamic priorities, where old pages have lower priority than newer ones
* Assign zero priority to standalone exercise pages for exercises that are included in a course chapter. This is to hide the standalone exercise pages from Google search.
**Why?**
These improvements were suggested by a teacher.
**How?**
Edited the ``sitemap.py`` files. See the code.
Fixes #975
Tested that the code does not produce errors by loading ``sitemap.xml`` in the browser.
=> Improve sitemaps with dynamic priorities

exercise/templates/exercise/_user_results.html
**What?**
Show hidden modules and exercises to teachers on "Your points" results page with a "hidden" label.
**Why?**
Teachers have requested easier access to hidden modules and exercises, such as enrollment questionnaires.
**How?**
Hidden modules are now shown to teachers and marked with a "hidden" label.
Fixes apluslms/a-plus-rst-tools#111
Fixes #449
Fixes #1012
Checked that everything works and looks good.
=> Show hidden modules and exercises to teachers on "Your points" page

locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po, userprofile/models.py, userprofile/templates/userprofile/profile.html, userprofile/urls.py, userprofile/views.py
**What?**
Previously, it was not possible for the user to regenerate a new API token in the user interface.
The user profile view now has a button for regenerating one.
**Why?**
This makes it easier to generate a new API token.
**How?**
A button was added to the userprofile page for regenerating the token.
Fixes #1022
Tested that regenerating the API token works.
=> Add button to regenerate the API access token

exercise/static/exercise/duplicate_check.js
**What?**
There was a bug where the exercise submit button did not do anything in exercises that were neither questionnaires or file submission exercises. This was due to a bug in the recently added duplicate submission checking feature.
This PR fixes the bug by removing the false expectation that the exercise has either files to submit or is a questionnaire.
Now the duplicate submission checking feature works on other types of exercises too, such as custom JavaScript exercises.
**Why?**
This was pointed out by a teacher in an internal ticket:
https://rt.cs.aalto.fi/Ticket/Display.html?id=21819
Fixes #1064
=> Fix duplicate check in exercises other than quiz or file submit

exercise/static/exercise/duplicate_check.js
**What?**
Duplicate submission modal was sometimes popping up when submitting non-duplicate submissions.
This was because the submitted forms may include duplicate field names, and `duplicate_check.js` only hashed the last one of the fields with a duplicate name.
**Why?**
This bug was found by a student and pointed out by a course teacher.
**How?**
`duplicate_check.js` now uses `serializeArray()` instead of `Object.fromEntries()` when extracting the form fields. `serializeArray()` does not get rid of the duplicate fields, therefore fixing the bug.
=> Fix duplicate submission check not hashing all duplicate form fields

course/permissions.py, exercise/permissions.py, exercise/tests.py
Before, the permission check would work by simply checking whether the module had opened yet. With this check, the module opening time is only checked if the exercise is not an enrollment question
Fixes #679
**What?**
This change adds a check for if the exercise is an enrolment question to CourseModulePermissionBase.
**Why?**
Enrolment questions should be accessible before the module is open
**How?**
Before the check for if the module is open, we check whether the exercise is an enrolment question. If this is the case, then we do not care if the module is open.
Fixes #679 
* How to [test …
=> Added enrollment question check to CourseModulePermissionBase

exercise/static/exercise/duplicate_check.js
**What?**
Fix the bug where after submitting to a chapter exercise, the feedback modal was not scrollable if duplicate submission confirmation modal appeared first.
**Why?**
This was an annoying bug that prevented from scrolling the exercise feedback.
**How?**
The duplicate submission modal is now hidden before the exercise feedback modal is opened, which causes the exercise feedback modal to have focus as it should.
Fixes #1093
Tested that the modals have correctly working focus now.
=> Fix chapter exercise feedback modal missing focus after duplicate check

exercise/static/exercise/duplicate_check.js
**What?**
Fix duplicate submission check JavaScript crashing when the exercise submission form included optional file upload fields and the user did not select any file.
**Why?**
The code should not crash when optional files are not selected.
**How?**
Optional files that aren't selected are now treated as empty files by the duplicate submission check code.
Fixes #1095
Tested that the code now works as intended.
=> Fix duplicate submission check crashing with optional files

course/templates/course/_course_cards.html
Before, when the _course_cards.html was created by a parent and condensed was set to true, the hidden label would not be visible. Now condensed cards also show the label. This was done through removing the "and not condensed" condition from the card template
**What?**
The archive now shows the red "Hidden from students" label on course cards
**Why?**
It is useful for those with the permissions to see hidden courses (such as admins) to know that their courses are hidden
**How?**
Before, condensed cards would hide the label. I removed the condensed check (and not condensed) to prevent this from happening.
Fixes #727 
I added a course instance which was hidden, and ensured that this had the "Hidden From Students" label on it, and courses which weren't …
=> _course_cards.html doesn't hide label when condensed

exercise/templates/exercise/staff/_submission_data_modal.html
When inspecting a submission and opening the submission details modal, this modal did not have the meta_data field of the Submission model.
**Why?**
This can help admins and teachers debug issues
**How?**
In the modal template, we iterate over the key value pairs of the meta_data dictionary and display the keys and values.
Fixes #614 
Made sure that the correct metadata values were displayed for the corresponding labels, ensured that the fallback (No values to display) works when the metadata is empty.
=> Metadata values added to the modal in the submission inspection

assets/js/aplus.js, exercise/static/exercise/chapter.js
This commit does not break the support for MathJax 2.x. Rather than unconditionally using the 2.x API (Hub.Queue([])) we instead check the version of MathJax and either use the old Hub.Queue implementation or the new promise based implementation of 3.x (MathJax.typesetPromise()). This conditional typesetting is defined once as a jQuery plugin in assets/js/aplus.js. This plugin expects the HTML element which should be typeset.
Fixes #871
**What?**
Added support for MathJax 3.x without breaking compatibility 2.x.
**Why?**
According to the MathJax documentation, 2.x will only be maintained and there will be no further development. 
"MathJax v2 will continue to be maintained as we work to move more features into version 3, but MathJax v2 likely will not see much further development, just …
=> Added support for MathJax 3.x

exercise/static/exercise/chapter.js, exercise/templates/exercise/exercise.html
By using an ajaxComplete exercises maintain position on the exercise even as content loads. The scroll listener allows the user to scroll freely and prevent the repeated focusing on the exercise as content loads.
Fixes #1028
**What?**
This change ensures that when the user clicks on a anchor link referencing an exercise (such as #chapter-exercise-1) the focus remains on the referenced exercise even when content loads and the page height changes.
*No user scrolling*
*With user scrolling (focusing on the exercise disables as soon as scrolling is detected)*
**Why?**
Before, when a user clicked on an anchor link and content above loaded, the page would scroll and the exercise which was referenced by the link would move down either off screen or out of focus of the user which can cause …
=> Anchor links work even when page height changes

exercise/templates/exercise/exercise_plain.html
Added a bootstrap tooltip to the "Show model solutions" button. The tooltips are only shown once to the user through the use of localStorage. This is to prevent the tooltips from becoming annoying, and there is no reason to draw attention to the tooltips more than once.
Fixes #856
**What?**
The first time the client comes across a "show model solutions" button, this button has a tooltip bringing the users attention to it.
**Why?**
There were reports that users didn't notice the model solutions button. By adding the tooltip users should notice this button better. By only showing this button once we also avoid this from becoming annoying and distracting.
**How?**
We first check if the user has seen the model solutions tooltips before. This can be checked from the user's localStorage, based …
=> Added tooltips to show model solutions buttons

aplus/settings.py, aplus/urls.py, course/templates/course/course_base.html, exercise/async_views.py, exercise/protocol/aplus.py, exercise/submission_models.py, exercise/templates/exercise/exercise_base.html, exercise/templates/exercise/submission.html, exercise/viewbase.py, exercise/views.py, lib/models.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po, lti_tool/templates/lti_tool/_lti_exercise_wait.html, lti_tool/templates/lti_tool/course_list.html, lti_tool/templates/lti_tool/exercise_list.html, lti_tool/templates/lti_tool/lti_base.html, lti_tool/templates/lti_tool/lti_course.html, lti_tool/templates/lti_tool/lti_exercise.html, lti_tool/templates/lti_tool/lti_module.html, lti_tool/templates/lti_tool/lti_submission.html, lti_tool/templates/lti_tool/module_list.html, lti_tool/urls.py, lti_tool/utils.py, lti_tool/views.py, requirements.txt, templates/base.html
This PR adds functionality to A+ that enables it to be used as an LTI 1.3 tool in Moodle and possibly other LTI platforms.
**Why?**
Historically, the [A+ Astra moodle plugin](https://github.com/apluslms/moodle-mod_astra) that enables A+ exercises to be used in Moodle, required updates whenever the deployed Moodle version changed. By using the LTI standard to add the functionality instead, we ensure compatibility through version updates.
**How?**
The PR adds LTI protocol specific urls, views, and templates that allow embedding A+ material in an LTI context, and allow users to submit exercises to be graded in A+, with grading results being sent back to the Moodle gradebook. LTI deep linking is also supported, allowing teachers to select content via a UI. …
=> Use A+ as an LTI 1.3 tool

course/models.py, course/templates/course/course_base.html, course/templatetags/course.py, course/views.py
**What?**
There is supposed to be a link to the newest visible course instance on old course instance pages. However, this link did not always appear at the top of the page.  The link only appeared when the page used the ``InstanceView`` since this view set the ``later_instance`` variable used by ``course_base.html``.
This has now been fixed by adding a ``later_instance`` property to the ``CourseInstance`` class, and using it in the HTML template.
**Why?**
Newer course instances are supposed to be recommended to students that accidentally end up in old course instance pages.
Fixes #1152
Tested that the link now appears on pages that use ``course_base.html``
=> Fix link to newest course instance not appearing in old course instances

course/models.py, course/staff_views.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
Show also the number of removed students in log and UI notification. If error occurs, show the course that was being fetched.
Closes #1157
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up your git commit history before submitting the pull …
=> Improve logging and output on SIS interactions

doc/LTI_TOOL.md, doc/lti_local_settings.py
Documentation for setting up the A+ LTI 1.3 tool development environment.
Created an environment from scratch based on these instructions and tested adding the tool in moodle, as well as adding an exercise and submitting one as a student to verify the environment works as expected.
=> Add LTI 1.3 tool documentation

exercise/async_views.py, exercise/exercise_models.py, exercise/forms.py
This, combined with https://github.com/acos-server/acos-aplus/pull/8, fixes an issue where A+ was unable to send points from ACOS back to the LTI platform when A+ was used as an LTI tool.
Fixes #1154
=> Implement way of sending Acos grading results to LTI platform

edit_course/operations/configure.py
**What?**
Change config variable name in a loop.
**Why?**
It was redefining another variable used later.
=> Fix publish_url not being called in configure

authorization/permissions.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po, selenium_test/test/locators.py, selenium_test/test/teacher_list_test.py, templates/403.html
**What?**
Improve the access denied message and 403 page.
- Make it more clear why user may not access certain pages.
- Make the texts more student friendly and less techy.
- Update the translations
Some translations were automatically formatted by ``makemessages``, which is why they look like they were edited.
**How?**
- Finish the previous PR #1106 by fixing some minor issues in it.
Fixes #858
Closes #1106
Tested that the messages and 403 page look as expected.
=> Improve access denied messages and 403 page

course/models.py
**What?**
It has turned out that Aalto's SISU API gateway occasionally returns an empty list for all courses queried using this API because of some malfunction. This causes all students to be removed from course enrollments (and a major hassle as a result). Therefore we have now added a check to the code to protect against this situation: if the response contains an empty participant list, it is ignored.
Additionally, the error handling now reports the error code more clearly in logs.
Fixes #1180
This fix was not tested, because of the difficulty of doing that, but I assume there are no problems.
=> Protect against buggy participants reports from Aalto SISU API

exercise/static/exercise/chapter.js
To support interactive code blocks to have exercise title frame.
**What?**
chapter.js is modified to support new element classes
[ANSWER HERE]
**Why?**
We need to have interactive code blocks that can be executed in A+ servers.
[ANSWER HERE]
**How?**
[ANSWER HERE]
- [X ] Manual testing.
- [ X] Chrome
- [ X] Firefox
**Think of what is …
=> interactive code to have frame and grading

course/models.py
SIS logging incorrectly counted earlier removed students as removed on every updated. Now it counts only those participants who were not removed earlier.
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up your git commit history before …
=> Fix the removed counts in SIS logging

course/models.py, edit_course/operations/configure.py
Add clarifying comments and missing type hints for configure() related things.
Could probably just push directly to master but let's do it the "right" way in case there is something more to clarify.
=> Add some comments and type hints for configuring

course/models.py
**What?**
Check that starting and ending time are not None.
**Why?**
Admin page crashed when creating new course instance with empty date fields.
**How?**
Check that starting and ending time are not None.
Fixes #1174
Did basic checks that it doesn't crash anymore and can still create new instances.
=> Check that starting and ending times are not None

exercise/cache/hierarchy.py, exercise/templates/exercise/_children.html
**What?**
Course exercises weren't normally listed in the ToC, but they appeared there if they were put into maintenance mode.
Modules' children that are in maintenance mode (LearningObject.status maintenance) are now hidden from the course table of contents. Modules are still shown in ToC even if they are in maintenance mode.
**Why?**
This change was requested by a teacher.
Fixes #1124
Fixes #438
Tested that module children were hidden from ToC if they were put into maintenance mode.
=> Hide maintenance-mode content from ToC

edit_course/operations/configure.py, edit_course/operations/tests.py
Fixed an issue that prevented removing categories through external sources (e.g. git manager). Configuring would raise a KeyError if the new configuration didn't have a category that was previously configured. Also added a test that removes and adds categories.
=> Fix exception when categories removed in new config

doc/LTI_1.3_PLATFORM.md
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
=> Documentation on LTI 1.3 platform configuration

assets/js/aplus.js, edit_course/tests.py, exercise/static/exercise/chapter.js, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po, templates/base.html
**What?**
Previously when the student's internet connection or MOOC-Grader was down, submitting a questionnaire resulted in the error message ``Connecting to the assessment service failed!`` to be displayed. A more suitable error message had existed, but it was not shown because of a bug.
This bug is now fixed by adding a timeout to the submit request (the request's failure handler is now properly called). The existing error message ``SUBMISSION_ERROR_ALERT_COMMUNICATION_ERROR_W_SERVICE`` was also modified to be more descriptive.
If A+ can't be reached, a submission is obviously not consumed by making the submit request. However, a submission is consumed if A+ receives the submit request, even if MOOC-Grader can't be reached. In this case, the submission is put into the ``Initialized`` …
=> Add timeout and better error message to quiz submit request

course/api/views.py, course/models.py
Fixes #1084 
This change adds caching to the CourseExercisesViewSet endpoint. The outputs of the endpoint (with caching) are shown below.
/api/v2/courses/1/exercises/
https://gist.github.com/EerikSaksi/fef85032e20e45b09f98f2851cc780b5
/api/v2/courses/1/exercises/1/
https://gist.github.com/EerikSaksi/caaeca53237b08f0acf8c16ee316582e
/api/v2/courses/1/exercises/123456/
https://gist.github.com/EerikSaksi/63378e65211c39f89cc2c4aaa400d924
**Why?**
It is inefficient to fetch the exercises for every user from the database separately. This change saves the exercises in memory to make this endpoint more efficient, and to reduce load on the database.
**How?**
Below are details of all the changes this request introduces, as well as possible improvements which could be considered before this is …
=> Add caching to /courses/<course_id>/exercises/

course/api/tests.py, lib/api/serializers.py
**What?**
In the API, change the html_url to use the display_url rather than the absolute_url of an object.
Also, slightly clarify and simplify code by using local function build_aplus_api rather than building the url using the request object.
**Why?**
Exercises are often embedded in chapters, and if that is the case, it's more convenient for the html_url to direct the user to the display_url, which links to the chapter if the exercise is embedded.
**How?**
Change HtmlViewField to use display_url rather than absolute_url.
Fixes [Jutut issue #29](https://github.com/apluslms/mooc-jutut/issues/29)
Fixes #1217
* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updatin …
=> Change html_url to use display_url in API

exercise/cache/points.py
**What?**
Include error submissions in CachedPoints, and prioritize INITIALIZED and WAITING over ERROR and REJECTED submissions when falling back to last submission in inspect views.
**Why?**
#1193
Fixes #1193
Tested that the best submission is prioritized, and INITIALIZED and WAITING are prioritized over ERROR and REJECTED when a best submission doesn't exist.
=> Fix 404 error in inspect submitter view

exercise/static/exercise/user_results.js, exercise/templates/exercise/_user_results.html, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
The automatic folding and hiding of expired course modules on the user results page was suboptimal and annoying for some students/teachers.
Old course modules are no longer hidden behind a button and folding is made optional with the use of a new "Expand all modules" button. Automatic scrolling takes the user to the first open module, unless the page contains previously unseen course news.
**Why?**
Improvements to course module folding were requested by a teacher.
**How?**
Local storage is used to save the state of the "Expand all modules" button and the course news strings for each course.
If the "Expand all modules" button is checked, all course modules will be expanded upon page load, even if they are expired or inaccessible.
If the page contains course news that aren't found …
=> Make course module folding optional and implement automatic scrolling

deviations/forms.py, deviations/viewbase.py, deviations/views.py, exercise/templates/exercise/_user_results.html, exercise/templates/exercise/staff/_deviationslink.html, exercise/templates/exercise/staff/inspect_submission.html, exercise/templatetags/exercise.py, lib/viewbase.py
**What?**
Adds buttons to the points and inspect submission pages that take the user directly to the add deadline deviations page with some appropriate fields prepopulated (submitter and exercise, module or neither)
**Why?**
#1123
**How?**
Set initial values from GET parameters
Fixes #1123
Closes #1122 as unnecessary
Tested that the buttons and GET parameters work.
=> Add "add deadline deviations" buttons to the points page

course/api/views.py, exercise/cache/content.py
**What?**
Add the learning object's hierarchical name to ``CachedContent`` and remove the regex hack in ``CourseExercisesViewSet``.
This fixes the hierarchical name for Roman content numbering, since the hierarchical name should always use Arabic numbering.
Fixes #1228
Tested that the API now returns correct hierarchical names for all numbering styles.
=> Add hierarchical name to CachedContent and remove regex hack

exercise/api/csv/tests.py, exercise/api/csv/views.py, exercise/static/exercise/results_staff.js, exercise/submission_models.py, exercise/templates/exercise/staff/results.html, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Add checkbox to the all results UI to include/exclude unconfirmed points and backend logic for it.
**Why?**
#941
**How?**
Add a filter to the submission query to filter out unconfirmed submissions.
Closes #941
Made unconfirmed submissions and checked that the filter leaves them out.
=> Separate unconfirmed points in all results data

course/templatetags/course.py, exercise/templates/exercise/_exercise_info.html, exercise/templates/exercise/_user_results.html, exercise/templates/exercise/exercise_plain.html, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Displays deadline extensions in the points page with a tag in the module heading and a clock icon next to each exercise.
**Why?**
Students and staff members see deadline extensions more easily.
**How?**
Adds two custom template tags that check if an exercise/module has a personal deadline.
Fixes #1119
- [] Selenium tests.
The deadline deviations are only shown on the points page when the module is open and the student has time left to submit the exercise. Works for both module are exercise deviations. Both students and staff members see the deviations.
Template blocks are not indented.
=> Display personal deadline extensions on a student’s points page

course/templatetags/base.py, exercise/submission_models.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po, templates/base.html
**What?**
- Previously, when there were many unfinished grading tasks in ``PendingSubmissions`` table, a globally visible "Grader is unstable" banner was shown in A+ on all pages. However, oftentimes the problem may have concerned a particular exercise and course, and the alert unnecessarily bothered teachers and students on other courses. The banner is therefore made course-specific, and only shows on courses that have more than ``GRADER_STABLE_THRESHOLD`` (``settings.py`` parameter) retries pending.
- Additionally, the banner identifies the exercises that have retries pending, since it seems that when problems start occurring, typically it has been a specific exercise that raises this condition.
Fixes #1146
Tested that the banner now appears only on …
=> Make 'grader is unstable' banner course specific

edit_course/course_forms.py, notification/cache.py
**What?**
Notifications could previously come from hidden course instances, which made it impossible to clear the notification icon due to `CourseVisiblePermission`.
This is now fixed by filtering courses that are not visible to students and invalidating the `CachedNotifications` when a course instance is made hidden.
Fixes #683
Tested that a student no longer sees notifications from hidden courses.
=> Hide student notifications from hidden course instances

exercise/submission_models.py
**What?**
The 'grader unstable' banner showed exercise names in multiple languages on multilingual courses, which made it look bad. Now, the exercise names are shown only in the currently selected language.
Fixes #1259
Tested that the exercise names are now shown only in the selected language.
=> Show only localized exercise name in grader unstable banner

assets/js/aplus.js
**What?**
Previously, the inspect submission page froze if line numbers were added to extremely long feedback/code. Line numbers are now added only if the feedback or code is shorter than 5000 lines.
- A page with ~5000 lines of feedback takes about 3 seconds to load with line numbers.
- A page with ~230 000 lines of feedback used to freeze the page. Now it loads fine, but without line numbers.
Fixes #1210
Tested that the inspect submission page no longer freezes.
=> Do not add line numbers to extremely long feedback or code

exercise/protocol/aplus.py, lib/remote_page.py
**What?**
Strip remote page language suffix only on multilingual courses.
**Why?**
The language suffix in remote page links should not be removed on single language courses, because it can break the links.
Fixes #1255
Tested that CS-A1143 links work correctly now
=> Strip remote page language suffix only on multilingual courses

exercise/templates/exercise/_submit_progress.html, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Error messages related to connection/communication issues have been improved and duplicates removed.
The new error messages are as follows:
- `EXERCISE_ERROR_COMMUNICATION` (Submit exercise or a questionnaire, when submitting takes too long. Does not send email to course staff):
```
An error occurred while sending the submission for grading. Make sure you're
connected to the internet. If a submission was consumed, the submission will
be automatically graded after the service is available again.
```
- `EXERCISE_SERVICE_ERROR_CONNECTION_FAILED` (When loading an exercise fails, e.g., MOOC-Grader is down. Sends error email to course staff):
```
Connecting to the assignment service failed! Course staff has been notified.
```
- `ASSESSMENT_SERVICE_ERROR_CONNECTION_FAILED` (When …
=> Improve and remove duplicate connection error strings

course/viewbase.py, course/views.py
Fixes #1266
Slightly modified from similar commit earlier pushed to master (#1267 )
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
=> Fix non-revealed chapters in ModuleView

exercise/static/exercise/results_staff.js, selenium_test/test/teacher_list_test.py, selenium_test/test_data.json
**What?**
Empty students IDs were displayed as null in the All results table
**How?**
Replace null with an em dash (—) for a user friendly view
Fixes #1272 
=> Change null to mdash on empty student ids in the All results table

exercise/static/exercise/chapter.js, exercise/static/exercise/duplicate_check.js
**What?**
Support the new option implemented in apluslms/a-plus-rst-tools#174 to disable duplicate submission check for individual questionnaires and submit exercises or the whole course.
**Why?**
Some exercises often expect the submissions to be identical, so always showing the confirmation dialog is unnecessary.
Fixes #1076
Tested that the new feature works as expected.
=> Support disabling duplicate submission check

exercise/reveal_states.py
**What?**
ModuleRevealState stores the exercises of the module. If the module has none, an empty list is passed to max function, which throws an exception.
**Why?**
It is unlikely that any chapter should be hidden before a module with no exercises is "completed". However, if a teacher does set a model solution to this kind of module, the site will crash.
**How?**
Check if the list is empty before feeding it to the max function.
The site does …
=> Fix ModuleRevealState crashing if it contains no exercises

course/templates/course/_siblings.html, exercise/viewbase.py
It was possible for next/previous navigation links to point chapters that were not accessible.
This pull request is made for 1.20 branch, to be published in a patch release.
**What?**
[ANSWER HERE]
**Why?**
[ANSWER HERE]
**How?**
[ANSWER HERE]
*Clean up your git commit …
=> Fix next/prev navigation with reveal rules

exercise/submission_models.py
**What?**
When a student submitted a large PDF file and it was incorrectly detected as non-binary data by the binaryornot library, the inspect submission page tried to render it and caused the page to load slowly.
This is now fixed by always classifying files ending with '.pdf' as non-binary data.
Fixes #1298
=> Always classify files ending with '.pdf' as binary

deviations/viewbase.py
**What?**
The course module name is no longer queried separately for each deviation. This reduces the number of performed queries significantly. Additionally, some large unnecessary attributes are no longer loaded.
**Why?**
The deviations list page loaded extremely slowly before. This should help with the problem.
Fixes #1302
=> Optimize inefficient database query in the deviation list view

deviations/templates/deviations/add_dl.html, deviations/viewbase.py, exercise/static/exercise/assessment.js, exercise/static/exercise/user_results.js, exercise/templates/exercise/staff/_deviationslink.html
**What?**
Previously, the cancel button always sent the user to the deadline deviation list page. Now, it sends the user to the page where they came from, if possible.
**Why?**
This was requested by a teacher.
Fixes #1278
Tested that redirection works after cancelling new deadline deviation on inspect submission page and user results page.
=> Redirect to previous page when cancelling new deadline deviation

assets/js/ajax_search_select.js
Fixes #1280
**What?**
In add deadline deviations form, the module field search was case sensitive.
**Why?**
getSearchResults(() function in ajax_search_select.js was using the default :contains (which is case sensitive) selector to select the module value.
**How?**
Defined a custom selector "icontains" in ajax_search_results.js file to select elements that contain a specific text substring, case-insensitively and replaced :contains with :icontains in getSearchResults().
Fixes #1280 
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+reques …
=> The module search under add deadline deviations is case sensitive

locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
[Teacher-facing UI message is technically incorrect in the Inspect view](https://github.com/apluslms/a-plus/issues/1269)
**Why?**
The Inspect view may claim that there are higher-scoring submissions, even though there aren’t.
Fixes # 1269
Changed the text and replicated the situation on aplus-manual. It's now showing the updated text, which better maps to the situation.
=> Teacher-facing UI message is technically incorrect in the Inspect view

exercise/async_views.py, exercise/exercise_models.py, exercise/forms.py
Add lti session id to the built service url for services such as ACOS. Fixes #1305.
Tested submitting ACOS exercises in the mycourses-test + aplus-test testing environment.
=> Add LTI session id to parameters sent to ACOS

course/templates/course/module.html, exercise/templates/exercise/_children.html, exercise/templates/exercise/_user_toc.html, exercise/templatetags/exercise.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
Fixes #1277
**What?**
A student’s points page displays personal deadline extensions, which is useful. But it might make sense to add a similar notification elsewhere in the A+ web UI as well.
**How?**
Now, the ToC view also shows labels for personal deadline extensions.
Fixes #1277 
*Clean up …
=> Show personal deadline extensions in ToC view

exercise/cache/points.py
Fixed an issue where not all user submissions would be shown for an exercise when the user had made submissions to another exercise in between. This was caused by unsorted data provided for the `groupby` function on the subsequent line - it requires data to be sorted by the key that's used for grouping.
Ran manual tests at minus.cs to verify that all user submissions are now shown.
=> Fix issue with querying user submissions that could cause some submissions to be hidden

course/templates/course/course_base.html
Fixes #1311
**What?**
Course has ended sticky alert padding causes UI bug with exercise anchor links
**Why?**
Exercises now result in a weird exercise frame UI bug after scrolling up:
**How?**
padding-top has been changed to margin-top
*Clean up your git commit history before submitting the …
=> Course has ended sticky alert padding causes UI bug with exercise anchor links

course/templates/course/course_base.html, course/templatetags/base.py, templates/base.html
Fixes #1309
**What?**
'Grader is unstable' banner might not be seen by the user 
**Why?**
'Grader is unstable' banner might not be seen by the user since it is at the top of the page
**How?**
Made similar to the ''Course has already ended" banner, that stays at the top of the viewport, while the user scrolls the page.
**Think of what is affected by these changes …
=> Grader is unstable banner might not be seen by the user

deviations/tests.py, deviations/viewbase.py, deviations/views.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
After adding or removing a deadline or submission deviation through the form, redirects back to the form instead of redirecting to the deviation list page.
**Why?**
The deviation lists load very slowly, especially in courses with many deviations like Programming 1. This is just a way to avoid visiting the deviation page. This mainly concerns the deadline deviation list but I added the same modifications to submission deviations as well for consistency.
**How?**
Changes the success urls of views.
Fixes #1122 (partly)
* How to [test …
=> Redirect back to form after adding or removing deviations

edit_course/views.py
**What?**
Build log URL did not update immediately when creating a new course instance in the A+ course settings, instead it used the build log URL from the previous course instance until the build was done.
It also did not update immediately when changing the Git Manager key in the Git Manager tab in A+ course settings.
This caused an error when attempting to view the build log in A+ while the course was still being built.
Fixes #1339
=> Fix build log URL updating slowly

exercise/cache/points.py
The logic for counting exercises as passed, and thus coloring the points badges, was previously changed as such that unpassed children caused the parent to count as not passed. This has now been changed to work similarly as before so that exercises / chapters only consider themselves unpassed if their own points-to-pass has been defined and the points threshold has not been reached --> status of children won't be considered.
Also fixed an issue where exercises with 0 submissions were making parents count as unpassed even if they didn't have points-to-pass defined. This is technically moot until deciding what to do with exercise-based points-to-pass.
The points-to-pass attribute on exercises as a concept is currently weird, since it doesn't affect passing modules at all, and the logic …
=> Fix issues with points badge colors

deviations/admin.py, deviations/forms.py, deviations/migrations/0006_rename_extra_minutes_deadlineruledeviation_extra_seconds.py, deviations/models.py, deviations/templates/deviations/list_dl.html, deviations/templates/deviations/override_dl.html, deviations/templatetags/deviations.py, deviations/tests.py, deviations/views.py, exercise/cache/points.py, exercise/exercise_models.py, exercise/management/commands/export_submissions.py, exercise/reveal_models.py, exercise/reveal_states.py, exercise/tests.py, exercise/tests_cache.py, lib/fields.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Saving deadline deviations as seconds instead of minutes
allows teachers to better set midnight deadlines, such as
23:59:59.
The minutes are no longer discarded, when a deadline deviation is made using a date.
**Testing**
Tested that the deviations work as expected using a docker image [ihalaij1/run-aplus-front:faketime](https://github.com/ihalaij1/run-aplus-front/commit/335f9ad477ee639d71cf67649953a1ba2cdf47f0) that allows changing of the internal time.
docker-compose.yml:
```
plus:
image: ihalaij1/run-aplus-front:faketime
environment:
FAKETIME: "@2024-01-01 23:55:00"
```
Fixes #1138
=> Save deadline deviations as seconds instead of minutes

news/templates/news/list.html, news/views.py
**What?**
Removed two leftover print calls and changed how the singular news remove button functions. Previously the button was sending a GET request which then edited the database which should not be done. This has now been changed such that it send a POST request instead. 
**Why?**
Improves code readability and functionality
**How?**
Added a javascript listener to the singular remove buttons that then sends the request and redirects back to the current page
**What type of test …
=> Fix issues with multilanguage news

apps/tests.py, course/api/tests.py, course/test_visibility_enroll.py, course/tests.py, deviations/tests.py, edit_course/tests.py, exercise/api/csv/tests.py, exercise/api/tests.py, exercise/tests.py, external_services/tests.py, lib/testdata.py, redirect_old_urls/tests.py, shibboleth_login/tests.py, threshold/tests.py, userprofile/api/tests.py, userprofile/tests.py
Fixes #1233
Use setUpTestData instead of setUp for creating test data for a-plus unit tests.
**What?**
Unit tests in a-plus have used the setUp method for creating database entries for tests, which causes them to be created and destroyed separately for each test inside a test class. There is an alternative method called setUpTestData, which only creates the entries once and reuses the data for the whole test class, resulting in a considerable speedup when running tests.
**Why?**
Current a-plus unit tests require roughly 1/3 of the time required before this change. On my laptop:
Using setUp: Ran 245 tests in 232.683s
Using setUpTestData: Ran 245 tests in 70.508s
**How?**
Basically the only thing changed is replacing the setUp instance methods with setUpTestData class methods. In a few …
=> Use setUpTestData in tests

course/test_visibility_enroll.py, exercise/api/views.py, exercise/exercise_models.py, exercise/tests.py, exercise/views.py, external_services/api/views.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
Fixes #1226
**What?**
check_submission_allowed messages all have the same severity
**Why?**
submission_check is given a flag whether it should print the strings as errors or warnings but this does not make sense
**How?**
The flag has been removed and severity is decided by the statement. …
=> check_submission_allowed messages all have the same severity

course/templatetags/base.py, templates/base.html
Fixes #1133
**What?**
Login should not take the user to the front page.
**Why?**
The user should be redirected to the same page they came from after login.
**How?**
The user is now being taken to the page it came from before logging in.
*Clean up your git commit history before submitting the …
=> Login should not take the user to the front page

exercise/staff_views.py, exercise/tests.py
Fixes #1196
**What?**
Submitters whose older work was already graded weren't skipped when pressing the "next submitter" link in manual assesment.
**Why?**
We shouldn't show a user whose work has already been graded even if they have later work.
**How?**
Rather than checking if the most recent submission has been graded, we skip submitters based on if any of their submissions for this exercise has been graded
Fixes #1196 
In addition to unit tests I ensured that after grading the latest assesment the next submitter link takes you correctly. I also manually added a grader to the older work of the first user and ensured that this user was skipped even if their latest submission wasn't graded.
**Think of what is affected by …
=> Skip submissions if any have been graded in next submitter view

exercise/staff_views.py, exercise/templates/exercise/staff/_submissions_table.html, exercise/templates/exercise/staff/inspect_submission.html, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
https://user-images.githubusercontent.com/46625399/226879785-4294ac4f-4f54-4ec0-8549-2aed7b087fce.mp4
Add counter of manually assessed users, showing the number of users that have been passed in the queue, remaining, and the percentage. This ratio and percentage are displayed on the link to assess the next user.
**Why?**
Gives teachers grading a sense of how much there is to grade, and how much has already been done.
**How?**
We first get the total number of submissions prior to filtering by time. After filtering by time, we again get the number of submissions to calculate how many submission the user has already viewed. We use these two values to show the ratio and calculate the percentage. We embed this as a session variable, because `NextUnassessedSubmitterView` redirects to …
=> Remaining submission counter

course/api/views.py, exercise/cache/basetypes.py
**What?**
Adds the field has_submittable_files to the exercises API, which is true for any exercise that has submittable files and else false.
**Why?**
Currently each exercise has to be checked separately to see if it is submittable, leading to a lot of unnecessary requests by the IntelliJ plugin. Having the field in the exercises endpoint speeds up loading and reduces requests.
**How?**
The form_spec in exercise_info is checked to see if any type is file. _generate_data in exercise/cache/basetypes.py does not have type info of exercises, so isinstance(lobj, ExerciseWithAttachment) does not work.
* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translat …
=> Add has_submittable_files to the exercises API endpoint

exercise/staff_views.py, exercise/templates/exercise/staff/_submissions_table.html, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Shows all submissions in submission modal, instead of first 50. Adds a button to only show first 50 submissions.
**Why?**
The teacher probably wants to see all submissions, not just the first 50.
**How?**
Shows all submissions, unless an additional query parameter is specified.
Fixes #923
Buttons "show latest x" and "show all" display the expected number of submissions.
If the user wants to see all submissions on the full page (instead of the modal), it is now two clicks away.
=> Show all submissions by default

exercise/staff_views.py
Fixed a division-by-zero issue in all submissions list when there are no submissions yet.
Checked that percentage shows 0 when value is 0/0, and that a correct value is shown when there are manually graded submissions.
=> Fix division-by-zero in all submissions list

exercise/api/views.py
**What?**
Fix issue where api endpoint GET /courses/<course_id>/points/ was showing the same list as GET /courses/<course_id>/students/. Now endpoint GET /courses/<course_id>/points/ gives the user a list of all students in a course and their points in the course.
**Why?**
Allows for easier parsing of points for Aalto Grades. 
**How?**
Changed which list is given to the listserializer
Fixes #1360
[ADD A DESCRIPTION ABOUT WHAT YOU TESTED …
=> Fix api endpoint for list of points

exercise/api/full_serializers.py, notification/views.py
**What?**
Sends an update to Jutut when a student has read a feedback response.
**Why?**
For urgent messages, teachers need to know whether the student has read the message.
**How?**
Send a post request to Jutut endpoint /feedback/ that is responsible for creating and updating Feedback instances based on feedback submissions in A+. Adds an attribute to Submission serializer that indicates whether there are unread feedback responses for that (feedback) submission.
Fixes https://github.com/apluslms/mooc-jutut/issues/40.
Has to be merged with https://github.com/apluslms/mooc-jutut/pull/105.
* …
=> Update to Jutut that a feedback response has been read

exercise/cache/basetypes.py, exercise/cache/points.py, exercise/tests.py
**What?**
Now also chapters that are marked as model answers for a module are hidden after the lifesupport time passes.
**Why?**
Model answers should be hidden after the course ends.
Should the message in the info tooltip inside a hidden chapter MODULE_MODEL_ANSWER_NOT_VISIBLE also be changed accordingly? Now it only says: "This chapter is hidden, since it contains model answers that have not been published yet." even if the course is ended. …
=> Hide module model answers on lifesupport

exercise/api/custom_serializers.py
**What?**
Add fields `max_points` and `max_points_by_difficulty `to the points API general information. This simplifies calculating relevant points in MOOC-Jutut. The `max_points` field was already provided in the API for modules, but not for the course as a whole, and the max points for each category/difficulty weren't in the API beforehand.
**Why?**
So [viewing points via Jutut](https://github.com/apluslms/mooc-jutut/pull/109) could work more efficiently
**How?**
Adding the fields `max_points` and `max_points_by_difficulty` to the API
* How to [test …
=> Add more info about max_points to points API

course/templates/course/_course_menu.html, course/templatetags/course.py, external_services/models.py
**What?**
Open menu links to external websites, such as https://google.com in a new tab, instead of in the current tab.
**Why?**
This problem was pointed out by a teacher.
Fixes #1392
=> Open menu links to external websites in a new tab

external_services/models.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Fix 502 error when a menu link has a service and URL with a scheme.
This PR also rearranges some of the translations, because running `manage.py makemessages` does that when new strings have been added without running the command previously.
Missing translation for `LABEL_REGRADE_WHEN_SEEN` was also added.
Fixes #1394
=> Fix 502 error when a menu link has a service and URL with a scheme

course/api/views.py
**What?**
List news to students in the API only after they are published
The API still lists all the news to course staff
and superusers before they are published.
**Why?**
This was requested by a course.
Fixes #1398
=> List news to students in the API only after they are published

userprofile/api/full_serializers.py, userprofile/api/tests.py
**What?**
Add courses where the user is an assistant to the API.
Previously, only the courses where the user is a teacher were listed in the API.
**Why?**
This was requested by a course.
Fixes #1397
=> Add courses where the user is an assistant to the API

exercise/api/csv/views.py, exercise/api/views.py, exercise/staff_views.py, exercise/templates/exercise/staff/_submissions_table.html, exercise/templates/exercise/staff/_submitters_table.html, exercise/templatetags/exercise.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Add submissions zip download feature.
The submissions can be downloaded per exercise from the UI or API URL `/api/v2/exercises/<exercise_id>/submissions/zip?best=yes`
The zip archive contains a metadata file `info.csv` and submissions with a specific naming scheme:
- If the submission was made by a group, the file name starts with all of the group's student IDs joined by `+` signs.
Otherwise, there is only one student ID.
- The student IDs are followed by an underscore and the file number, since some exercises accept multiple files.
- The file number is followed by an underscore and the number of the submission, since users can have multiple submissions to the same exercise.
Example file names in an exercise requiring two submitted files:
```
123123_file1_submission1 …
```
=> Add submissions zip download feature

course/templates/course/_course_menu.html
**What?**
All the menu items that have being set an empty menu group label will automatically categorized to lastest added menu group on the sidebar menu.
**How?**
~~1. Adding a `student_groups_without_label` group in `CachedCourseMenu` View and append it always at the beginning of the `student_link_groups`. As a result they will always appear on the top of list.
2. Fixing the rendering logic of the corresponding template.~~
1. Show the menu items without labels before any other labels. As a result, the menu items without a label are rendered directly under the `Course` heading.
Fixes #1411  …
=> fix: move menu items with an empty group label under Course section

external_services/views.py
**What?**
Fix external links missing URL fragments if accessed by `http://localhost:8000/def/current/external-link/<menu_id>`.
The URL fragments were intact if the link was accessed through `http://localhost:8000/def/current/lti-login/<menu_id>` or by clicking the link in the menu. Therefore, the issue #873 has been mostly fixed for a while now.
Closes #873
=> Fix external links sometimes missing URL fragments

deviations/templates/deviations/override_dl.html, deviations/views.py
**What?**
PR #1346 did not apply daylight savings time consideration when overriding previous deadline deviations, but only when creating entirely new deadline deviations.
After these changes, daylight savings time consideration is applied also when overriding old deadline deviations.
Fixes #1287
=> Fix overriding deadline deviations around daylight savings border

exercise/api/views.py
**What?**
Added some columns to the info.csv. These are useful for the ImGPT tool as well as Radar/Dolos.
**Why?**
See above
**How?**
Added rows. All things are fetched through database queries. Seems quite fast from my testing
Fixes #1427
*Clean up your git commit history before submitting …
=> Add more data to info.csv from zip download

course/templates/course/_course_menu.html, course/templatetags/course.py
**What?**
List all available course languages in the dropdown menus for desktop and mobile, with the active language marked with a checkmark.
Fixes #849
=> Display currently selected course language

exercise/static/exercise/results_staff.js
Added the email field in "All results" pages CSV and other exports.
**Why?**
Requested by teachers.
Fixes #1428
Downloaded the CSV export and checked the students' emails were there. Also tested that an empty email address doesn't break the export.
=> Add student email to 'All results' page's CSV, Copy, and Excel downloads

edit_course/templates/edit_course/build_log.html, edit_course/templatetags/editcourse.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
Clarify times and time zones related to course updates and builds, by making the strings more clear and matching time zones between A+ and Git manager.
**OLD**:
**NEW**:
**Why?**
Unclear string and Git manager using UTC time has caused confusion before.
Fixes #1128
=> Clarify times and time zones related to course updates and builds

course/templates/course/staff/all_submissions_table.html, exercise/staff_views.py, exercise/templates/exercise/module_goal_modal.html, exercise/templates/exercise/staff/_submissions_table.html, exercise/templates/exercise/staff/inspect_submission.html, exercise/tests.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po
**What?**
* Bugs in the NextUnassessedSubmitterView were previously fixed in PR #1413. However, the previous fixes removed the possibility to skip submitters. These changes re-implement skipping, but this time a bit differently.
* Also fixed issues with multiple translations being "fuzzy" after running `makemessages`
**Why?**
The skip functionality was requested to be brought back.
**How?**
Skipped submitters are saved to the session, so that we can keep track of them.
Fixes #1439
Tested the functionality with multiple submissions. Skipping was working well, and the submitters were correctly looped through.
=> Allow user to skip submitters when using manual assessment

exercise/exercise_models.py
The "Visit site without sending data" link directed to the wrong page (the exercise's page itself on A+) due to copy-pasted code. This fixes that.
Fixes #1447 
Made an LTI1.3 exercise and checked the link pointed to a sensible place.
=> Fix incorrect url for 'visit without sending data' in lti1.3 services

course/templates/course/course.html
**What?**
Fix 'Continue where you left off' exercise name HTML escape.
**Why?**
This broke, for example, apostrophes in exercise names.
**How?**
Use django's `|safe` filter instead of a javascript function for escape.
Fixes #1432
=> Fix 'Continue where you left off' exercise name HTML escape

course/templates/course/_course_menu.html, course/templates/course/staff/all_submissions_table.html, course/views.py
**What?**
* Limit the table rows to 50 by default and fetch exercise objects in the same query with the submissions.
* Pagination should be added to the page later.
Adding `select_related('exercise')` improved the performance, when loading the page limited to 50 table rows.
In local testing it loaded ~2x faster with around 100 submissions with `select_related`, vs. without it.
Part of #1448
=> Improve performance of "All submissions" view

course/admin.py, exercise/admin.py, exercise/api/views.py
**What?**
* Add SubmissionTag and SubmissionTagging to Django admin site
* Add API endpoint for adding and deleting submission taggings
API usage:
`POST /submissions/<submission_id>/tag/`: tags a submission with a submission tag.
- Request body:
- `tag_slug`: the slug of the tag to be added.
`DELETE /submissions/<submission_id>/tag/`: removes a submission tag from a submission.
- Request body:
- `tag_slug`: the slug of the tag to be removed.
Fixes #1430
Tested that the API endpoints seem to work by sending POST and DELETE requests with Postman.
=> Add API endpoints for adding and deleting submission taggings

exercise/api/csv/views.py
**What?**
Remove duplicates from submissiondata API endpoint, because group submissions caused data to be duplicated.
Tested that the duplicates are no longer present in data downloaded from a URL such as http://localhost:8000/api/v2/courses/1/submissiondata/?exercise_id=29&format=json&best=no
Fixes #1285
=> Remove duplicates from submissiondata API endpoint
